local monarch = require "monarch.monarch"
local Input = require('core.systems.input')
local SoundController = require('core.components.sound_controller')

function init(self)
    msg.post(".", "acquire_input_focus")

end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id == Input.BACK and action.pressed then
        monarch.back()
        print('won!')
    end
end

function on_reload(self)
end
