local monarch = require "monarch.monarch"
local druid = require("druid.druid")
local Input = require('core.systems.input')
local SoundController = require('core.components.sound_controller')
local selection_menu_widget = require('ui.widgets.selection_menu.selection_menu')

function init(self)
    msg.post(".", "acquire_input_focus")
    self.druid = druid.new(self)
    self.selection_menu_widget = self.druid:new_widget(selection_menu_widget)
    local data = {'fight', 'ability', 'run'}
    self.selection_menu_widget:set_data(data)
    self.selection_menu_widget.on_option_select:subscribe(on_menu_option_select, self)

    self.root_node = gui.get_node('root')
    appear(self)
end

function final(self)
    self.druid:final()
end

function update(self, dt)
    self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
    self.druid:on_message(message_id, message, sender)
    
end

function on_input(self, action_id, action)
    return self.druid:on_input(action_id, action)
end

on_menu_option_select = function (self, index)
    if index == 1 then
        print("攻击！")
    elseif index == 2 then
        print("能力！")
    elseif index == 3 then
        print("逃跑！")
        monarch.back()
    end
end

appear = function(self)
    print('animate!')
    gui.set_scale(self.root_node, vmath.vector3())
    gui.animate(self.root_node, 'scale', vmath.vector3(1), go.EASING_OUTBACK, 0.2)
end
