local StateMachine = require('lib.thirdparty.statemachine')
local Input = require('core.systems.input')

-- 引入状态模块
local StateIdle = require('game.entities.player.states.player_idle')
local StateRun = require('game.entities.player.states.player_run')


---@package
---@param self player.script
function init(self)
	msg.post('.', 'acquire_input_focus')

	self.move_speed = 300
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()
	self.facing = vmath.vector3(0, -1, 0)

	-- 建立状态映射表
	self.states = {
		idle = StateIdle,
		running = StateRun,
	}

	self.fsm = StateMachine.create({
		initial = 'idle',
		events = {
			{ name = 'move', from = 'idle', to = 'running' },
			{ name = 'stop', from = 'running', to = 'idle'},
		},
		callbacks = {
			onstatechange = function (fsm, event, from, to)
				print('State Change: [' .. event .. ']' .. from .. '-->' .. to)

				-- A.退出旧状态
				local old_state = self.states[from]
				if old_state and old_state.exit then
					old_state.exit(self)
				end

				-- B.切换当前状态指针
				self.current_state = self.states[to]

				-- C.进入新状态
				if self.current_state and self.current_state.enter then
					self.current_state.enter(self)
				end
			end
		}
	})

	-- 手动初始化第一个状态
	self.current_state = self.states['idle']
	self.current_state.enter(self)
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
	-- 处理输入向量归一化
	if vmath.length(self.direction) > 1 then
		self.direction = vmath.normalize(self.direction)
	end

	-- 处理朝向
	if vmath.length(self.direction) > 0 then
		self.facing = self.direction
	end

	-- 委托update逻辑给当前状态
	if self.current_state and self.current_state.update then
		self.current_state.update(self, dt)
	end

	local pos = go.get_position()
	pos = pos + self.velocity * dt
	print(self.velocity)
	go.set_position(pos)

	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	if 	   action_id == Input.UP    then self.direction.y =  1
	elseif action_id == Input.DOWN  then self.direction.y = -1
	elseif action_id == Input.LEFT  then self.direction.x = -1
	elseif action_id == Input.RIGHT then self.direction.x =  1
	end
end