local StateMachine = require('lib.thirdparty.statemachine')
local Input = require('core.systems.input')
local game_data = require('data.config.game_data')

-- 引入状态模块
local StateIdle = require('game.entities.player.states.player_idle')
local StateRun = require('game.entities.player.states.player_run')
local StateAttack = require('game.entities.player.states.player_attack')

local function setup_and_disable_hitbox(self)
	self.hitboxes = {
		up = msg.url('#hitbox_up'),
		down = msg.url('#hitbox_down'),
		left = msg.url('#hitbox_left'),
		right = msg.url('#hitbox_right')
	}
	
	for _, url in pairs(self.hitboxes) do
		msg.post(url, 'disable')
	end
end


---@package
---@param self player.script
function init(self)
	msg.post('.', 'acquire_input_focus')

	setup_and_disable_hitbox(self)

	self.hp = game_data.player_hp

	self.move_speed = 300
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()
	self.facing = vmath.vector3(0, -1, 0)
	
	self.input_pressed_attack = false
	self.invincible = false

	-- 建立状态映射表
	self.states = {
		idle = StateIdle,
		running = StateRun,
		attacking = StateAttack
	}

	self.fsm = StateMachine.create({
		initial = 'idle',
		events = {
			{ name = 'move', from = { 'idle', 'attacking' }	, to = 'running' },
			{ name = 'stop',   from = { 'running', 'attacking' }, to = 'idle' },
			{ name = 'attack', from = { 'idle', 'running'}, to = 'attacking'},
			{ name = 'hurt', from = '*', to = 'hurting'},
		},
		callbacks = {
			onstatechange = function (fsm, event, from, to)
				print('State Change: [' .. event .. ']' .. from .. '-->' .. to)

				-- A.退出旧状态
				local old_state = self.states[from]
				if old_state and old_state.exit then
					old_state.exit(self)
				end

				-- B.切换当前状态指针
				self.current_state = self.states[to]

				-- C.进入新状态
				if self.current_state and self.current_state.enter then
					self.current_state.enter(self)
				end
			end
		}
	})

	-- 手动初始化第一个状态
	self.current_state = self.states['idle']
	self.current_state.enter(self)
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
	-- 处理输入向量归一化
	if vmath.length(self.direction) > 1 then
		self.direction = vmath.normalize(self.direction)
	end

	-- 处理朝向
	if vmath.length(self.direction) > 0 then
		self.facing = vmath.vector3(self.direction)
	end

	-- 委托update逻辑给当前状态
	if self.current_state and self.current_state.update then
		self.current_state.update(self, dt)
	end

	-- 对于 “中断型行为” (Interrupts) 比如攻击、受伤、冲刺
	-- 我们通常采用 “全局劫持” (Global Interception) 模式。
	if self.input_pressed_attack and self.fsm:can('attack') then
		self.fsm:attack()
		self.input_pressed_attack = false
	end

	-- 应用物理
	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)

	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()

	if self.hp <= 0 then
		msg.post('/monarch', 'player_dead')
	end
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	if self.current_state and self.current_state.on_message then
		self.current_state.on_message(self, message_id, message, sender)
	end

	if message_id == hash('collision_response') and message.group == hash('enemies') then
		if not self.invincible then
			self.hp = self.hp - 1
		end
		self.invincible = true
		timer.delay(2, false, function ()
			self.invincible = false
		end)
		print(self.hp)
	end

	if message_id == hash('contact_point_response') and message.group == hash('wall') then
		local pos = go.get_position()
		local new_pos = pos + message.normal * message.distance
		go.set_position(new_pos)
	end
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	if 	   action_id == Input.UP    then self.direction.y =  1
	elseif action_id == Input.DOWN  then self.direction.y = -1
	elseif action_id == Input.LEFT  then self.direction.x = -1
	elseif action_id == Input.RIGHT then self.direction.x =  1
	end

	if action_id == Input.ATTACK then
		if action.pressed then
			self.input_pressed_attack = true
		end
	end
end