local StateMachine = require('lib.thirdparty.statemachine')
local Input = require('core.systems.input')
local game_data = require('data.config.game_data')

-- 引入状态模块
local StateIdle = require('game.entities.player.states.player_idle')
local StateRun = require('game.entities.player.states.player_run')
local StateAttack = require('game.entities.player.states.player_attack')

local function setup_and_disable_hitbox(self)
	self.hitboxes = {
		up = msg.url('#hitbox_up'),
		down = msg.url('#hitbox_down'),
		left = msg.url('#hitbox_left'),
		right = msg.url('#hitbox_right')
	}
	
	for _, url in pairs(self.hitboxes) do
		msg.post(url, 'disable')
	end
end

local function auto_walk(self, message)
	msg.post('#collision', 'disable')
	local move_dir = message.direction -- 这是一个 vector3，例如 (0, 1, 0)
        
	-- 1. 进入托管模式
	self.input_enabled = false
	
	-- 2. 播放走路动画 (视觉上不能滑步)
	-- 假设你有一个根据方向播放动画的辅助函数 play_walk_anim(dir)
	-- 或者简单的写：
	if move_dir.y > 0 then sprite.play_flipbook("#sprite", "walk_up")
	elseif move_dir.y < 0 then sprite.play_flipbook("#sprite", "walk_down")
	elseif move_dir.x > 0 then sprite.play_flipbook("#sprite", "walk_right")
	elseif move_dir.x < 0 then sprite.play_flipbook("#sprite", "walk_left")
	end
	
	-- 3. 计算目标位置
	-- 比如让玩家往门里走 48 个像素 (约 1.5 格)
	local distance = 48 * 9
	local current_pos = go.get_position()
	local target_pos = current_pos + (move_dir * distance)
	
	-- 4. 执行位移
	-- 时间建议和相机移动时间保持一致，或者稍微短一点
	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, target_pos, go.EASING_LINEAR, 1.5, 0, function()  end)
end


---@package
---@param self player.script
function init(self)
	msg.post('.', 'acquire_input_focus')
	self.input_enabled = true

	setup_and_disable_hitbox(self)

	self.hp = game_data.player_hp

	self.move_speed = 300
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()
	self.facing = vmath.vector3(0, -1, 0)
	
	self.input_pressed_attack = false
	self.invincible = false

	-- 建立状态映射表
	self.states = {
		idle = StateIdle,
		running = StateRun,
		attacking = StateAttack
	}

	self.fsm = StateMachine.create({
		initial = 'idle',
		events = {
			{ name = 'move', from = { 'idle', 'attacking' }	, to = 'running' },
			{ name = 'stop',   from = { 'running', 'attacking' }, to = 'idle' },
			{ name = 'attack', from = { 'idle', 'running'}, to = 'attacking'},
			{ name = 'hurt', from = '*', to = 'hurting'},
		},
		callbacks = {
			onstatechange = function (fsm, event, from, to)
				-- print('State Change: [' .. event .. ']' .. from .. '-->' .. to)

				-- A.退出旧状态
				local old_state = self.states[from]
				if old_state and old_state.exit then
					old_state.exit(self)
				end

				-- B.切换当前状态指针
				self.current_state = self.states[to]

				-- C.进入新状态
				if self.current_state and self.current_state.enter then
					self.current_state.enter(self)
				end
			end
		}
	})

	-- 手动初始化第一个状态
	self.current_state = self.states['idle']
	self.current_state.enter(self)
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
	if not self.input_enabled then
		return
	end

	-- 处理输入向量归一化
	if vmath.length(self.direction) > 1 then
		self.direction = vmath.normalize(self.direction)
	end

	-- 处理朝向
	if vmath.length(self.direction) > 0 then
		self.facing = vmath.vector3(self.direction)
	end

	-- 委托update逻辑给当前状态
	if self.current_state and self.current_state.update then
		self.current_state.update(self, dt)
	end

	-- 对于 “中断型行为” (Interrupts) 比如攻击、受伤、冲刺
	-- 我们通常采用 “全局劫持” (Global Interception) 模式。
	if self.input_pressed_attack and self.fsm:can('attack') then
		self.fsm:attack()
		self.input_pressed_attack = false
	end

	-- 应用物理
	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)

	self.direction = vmath.vector3()
	self.velocity = vmath.vector3()

	if self.hp <= 0 then
		msg.post('/monarch', 'player_dead')
	end
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	if self.current_state and self.current_state.on_message then
		self.current_state.on_message(self, message_id, message, sender)
	end

	if message_id == hash('collision_response') and message.group == hash('enemies') then
		if not self.invincible then
			self.hp = self.hp - 1
		end
		self.invincible = true
		timer.delay(2, false, function ()
			self.invincible = false
		end)
	end

	if message_id == hash('contact_point_response') and message.group == hash('wall') then
		local pos = go.get_position()
		local new_pos = pos + message.normal * message.distance
		go.set_position(new_pos)
	end

	if message_id == hash('transition_camera_start') then
		self.input_enabled = false
	elseif message_id == hash('transition_camera_end') then
		self.input_enabled = true
		msg.post('#collision', 'enable')
	end

	if message_id == hash('auto_walk') then
		auto_walk(self, message)
	end
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	local deadzone = 0.2
	if action_id == Input.UP and action.value > deadzone then self.direction.y = 1
	elseif action_id == Input.DOWN and action.value > deadzone then self.direction.y = -1
	elseif action_id == Input.LEFT and action.value > deadzone then self.direction.x = -1
	elseif action_id == Input.RIGHT and action.value > deadzone then self.direction.x =  1
	end

	if action_id == Input.ATTACK then
		if action.pressed then
			self.input_pressed_attack = true
		end
	end
end