local GameData = require('data.config.game_data')
local utils = require('core.utils.utils')

local tile_size = GameData.tile_size
local bg_size = GameData.bg_size
local tilemap_width = GameData.tilemap_width
local tilemap_height = GameData.tilemap_height


local reward_brick_height = 10


local function create_backgroud()
    for x = 0, tilemap_width - 1 do
        local local_pos = utils.tile_to_screen(x, 0, bg_size)
        local_pos.y, local_pos.z = 300, -0.8
        local id = collectionfactory.create('#factory_level_maker_sky', local_pos, nil)
    end
end

local function create_flag(self)
    local x = math.random(100, 110)
    local tilemap = GameData.tilemap
    local top_tile = tilemap.tile[x][tilemap_height - 1]
    local local_pos = utils.tile_to_screen(x, tilemap_height, tile_size)
    
    if top_tile.type == 1 or nil then
        local id = factory.create('#factory_level_maker_flag', local_pos)
        print('flag genrated!')
        tilemap.tile[x][tilemap_height] = {
            id = id,
            x = x,
            y = tilemap_height,
            type = 4
        }
    end
end

local function create_reward_brick(self)
    local tilemap = GameData.tilemap

    for x = 0, tilemap_width - 1 do
        if tilemap.tile[x] then
            if math.random(10) == 1 then
            local local_pos = utils.tile_to_screen(x, reward_brick_height, tile_size)
            local id = factory.create('#factory_level_maker_reward_brick', local_pos, nil)
            tilemap.tile[x][reward_brick_height] = {
                id = id,
                x = x,
                y = reward_brick_height,
                type = 3
            }
            end
        end
    end
end


local function create_pillar(self)
    local tilemap = GameData.tilemap
    local last_pillar_x = -999
    local min_pillar_distance = 5

    for x = 0, tilemap_width - 1 do
        local has_ground = tilemap.tile[x]
        

        if has_ground then
            local distance = x - last_pillar_x

            if math.random(5) == 1 and distance >= min_pillar_distance then
                local pillar_height = math.random(1, 3)
                local start_y = tilemap_height - 1
                local end_y = tilemap_height - 1 + pillar_height
                for y = start_y, end_y do
                    local local_pos = utils.tile_to_screen(x, y, tile_size)
                    local id = factory.create('#factory_level_maker_pillar', local_pos, nil, { type = 0 })
                    tilemap.tile[x][y] = {
                        id = id,
                        x = x,
                        y = y,
                        type = 2
                    }
                end

                last_pillar_x = x
                print(last_pillar_x)
            end
        end
    end
end

local function create_tilemap(self)
    local tilemap = {
        tile_size = tile_size,
        width = tilemap_width,
        height = tilemap_height,
        tile = {}
    }

    for x = 0, tilemap_width - 1 do
        if math.random(7) > 1 then
            tilemap.tile[x] = {}

            for y = 0, tilemap_height - 1 do
                local local_pos = utils.tile_to_screen(x, y, tile_size)
                local id

                if y >= tilemap_height - 1 then
                    id = factory.create('#factory_level_maker_tile_top', local_pos, nil, { type = 1 })
                else
                    id = factory.create('#factory_level_maker_tile', local_pos, nil, { type = 0 })
                end

                tilemap.tile[x][y] = {
                    id = id,
                    x = x,
                    y = y,
                    type = 1
                }

            end
        else
            tilemap.tile[x] = nil
        end
    end

    return tilemap
end

---@package
---@param self level_maker.script
function init(self)
    math.randomseed(os.time())
    msg.post('#', 'start_level')
end

---@package
---@param self level_maker.script
---@param message_id hash
---@param message table
---@param sender 'factory.level_maker'
function on_message(self, message_id, message, sender)
    if message_id == hash('start_level') then
        GameData.tilemap = create_tilemap(self)
        create_backgroud()
        create_pillar(self)
        create_reward_brick(self)
        create_flag(self)
    end
end