local GameData = require('data.config.game_data')
local utils = require('core.utils.utils')

local tile_size = GameData.tile_size
local bg_size = GameData.bg_size
local tilemap_width = GameData.tilemap_width
local tilemap_height = GameData.tilemap_height


local reward_brick_height = 10


local function create_backgroud()
    for x = 0, tilemap_width - 1 do
        local local_pos = utils.tile_to_screen(x, 0, bg_size)
        local_pos.y, local_pos.z = 300, -0.8
        local id = collectionfactory.create('#factory_level_maker_sky', local_pos, nil)
    end
end

local function create_pyramid(flag_x)
    local tilemap = GameData.tilemap

    -- 1. 配置参数
    local peak_x = flag_x - 2 -- 金字塔最高点的 X 坐标 (紧贴旗杆左侧)
    local max_height = 8      -- 金字塔最高点的高度

    -- 2. 核心循环：使用偏移量 i
    -- i 代表“当前列距离最高点有多远”
    -- 当 i = 0 时，我们在最高点，高度 = 8
    -- 当 i = 1 时，我们在左边一格，高度 = 7
    for i = 0, max_height - 1 do
        -- A. 算出当前列的 X 坐标 (从右向左延伸)
        local current_x = peak_x - i

        -- B. 算出当前列的高度 (距离越远，高度越低)
        local current_h = max_height - i

        -- [防御性编程] 确保这一列在地基范围内，防止数组越界报错
        if tilemap.tile[current_x] then

            for y = tilemap_height, tilemap_height + current_h - 1 do
                local local_pos = utils.tile_to_screen(current_x, y, tile_size)
                local id = factory.create('#factory_level_maker_block', local_pos)
                tilemap.tile[current_x][y] = {
                    id = id,
                    x = current_x,
                    y = y,
                    type = 5
                }
            end
        end
    end
end


local function create_flag(self)
    local start_search_x = math.random(100, 120)
    local tilemap = GameData.tilemap
    local ground_y = tilemap_height - 1
    local flag_y = tilemap_height

    for x = start_search_x, 0, -1 do
        local column = tilemap.tile[x]

        if column then
            local ground_tile = column[ground_y]

            if ground_tile and ground_tile.type == 1 then
                local local_pos = utils.tile_to_screen(x, flag_y, tile_size)
                local id = factory.create('#factory_level_maker_flag', local_pos)
                print('flag genrated!')
                tilemap.tile[x][flag_y] = {
                    id = id,
                    x = x,
                    y = flag_y,
                    type = 4
                }
                create_pyramid(x)
            end

            return
        end
    end
end

local function create_reward_brick(self)
    local tilemap = GameData.tilemap

    for x = 0, tilemap_width - 1 do
        if tilemap.tile[x] then
            if math.random(10) == 1 then
            local local_pos = utils.tile_to_screen(x, reward_brick_height, tile_size)
            local id = factory.create('#factory_level_maker_reward_brick', local_pos, nil)
            tilemap.tile[x][reward_brick_height] = {
                id = id,
                x = x,
                y = reward_brick_height,
                type = 3
            }
            end
        end
    end
end


local function create_pillar(self)
    local tilemap = GameData.tilemap
    local last_pillar_x = -999
    local min_pillar_distance = 5

    -- 状态记忆变量
    local pillar_remaining = 0
    local current_pillar_height = 0

    for x = 0, tilemap_width - 1 do
        local has_ground = tilemap.tile[x]
        
        -- 只有当地面存在时，我们才考虑柱子逻辑
        -- 如果遇到深渊，强制中断柱子生成（安全机制）
        if has_ground then
            -- 情况A 正在生成未完成的宽柱子
            if pillar_remaining > 0 then
                local start_y = tilemap_height - 1
                local end_y = tilemap_height - 1 + current_pillar_height
                
                -- 执行生成
                for y = start_y, end_y do
                    local id
                    local local_pos = utils.tile_to_screen(x, y, tile_size)
                    
                    if y >= end_y then
                        id = factory.create('#factory_level_maker_tile_top', local_pos, nil)
                    end
                    
                    id = factory.create('#factory_level_maker_pillar', local_pos, nil)
                    tilemap.tile[x][y] = {
                        id = id,
                        x = x,
                        y = y,
                        type = 2
                    }
                end

                -- 计数器减一
                pillar_remaining = pillar_remaining - 1
                -- 更新最后柱子位置
                last_pillar_x = x
                
            -- 情况B 没有生成队列，判断是否开始新的生成队列
            else
                local distance = x - last_pillar_x

                if distance > min_pillar_distance and math.random(5) == 1 then
                    -- 决定柱子的属性，宽和高
                    local pillar_width = math.random(2, 3)
                    local pillar_height = math.random(1, 3)

                    -- 启动生成状态
                    pillar_remaining = pillar_width
                    current_pillar_height = pillar_height

                    -- 生成宽度的第一列
                    local start_y = tilemap_height - 1
                    local end_y = tilemap_height - 1 + current_pillar_height
                    for y = start_y, end_y do
                        local local_pos = utils.tile_to_screen(x, y, tile_size)
                        local id = factory.create('#factory_level_maker_pillar', local_pos, nil)
                        tilemap.tile[x][y] = { 
                            id = id,
                            x = x,
                            y = y,
                            type = 2
                        }
                    end

                    -- 消耗掉 1 格宽度
                    pillar_remaining = pillar_remaining - 1
                    last_pillar_x = x
                end
            end

        else
            -- 如果这格是深渊，强制重置柱子状态
            pillar_remaining = 0
        end
    end
end

local function create_tilemap(self)
    local tilemap = {
        tile_size = tile_size,
        width = tilemap_width,
        height = tilemap_height,
        tile = {}
    }

    -- [状态记忆变量]
    local chasm_remaining = 0 -- 如果大于0，说明当前正在生成深渊
    local safe_zone = 10    -- 初始安全区，开局 10 格必须是地面

    for x = 0, tilemap_width - 1 do
        -- 逻辑判断：这一格应该是深渊么？
        local make_chasm = false

        if chasm_remaining > 0 then
            -- A. 如果正处于深渊生成模式中，继续造深渊
            make_chasm = true
            chasm_remaining = chasm_remaining - 1
        elseif safe_zone > 0 then
            -- B. 如果处于安全区，强制造地面
            make_chasm = false
            safe_zone = safe_zone - 1
        else
            -- C. 既不是深渊模式，也不在安全区，那就掷骰子决定是否开始新深渊
            if math.random(10) == 1 then
                make_chasm = true
                -- 决定深渊狂赌
                chasm_remaining = math.random(2, 4)
                -- 扣掉当前这一格
                chasm_remaining = chasm_remaining - 1
                -- 设定下一个安全区，至少6格地面
                safe_zone = 6
            end
        end

        -- 执行生成
        if not make_chasm then
            tilemap.tile[x] = {}

            for y = 0, tilemap_height - 1 do
                local local_pos = utils.tile_to_screen(x, y, tile_size)
                local id

                if y >= tilemap_height - 1 then
                    id = factory.create('#factory_level_maker_tile_top', local_pos, nil, { type = 1 })
                else
                    id = factory.create('#factory_level_maker_tile', local_pos, nil, { type = 0 })
                end

                tilemap.tile[x][y] = {
                    id = id,
                    x = x,
                    y = y,
                    type = 1
                }

            end
        else
            tilemap.tile[x] = nil
        end
    end

    return tilemap
end

---@package
---@param self level_maker.script
function init(self)
    math.randomseed(os.time())
    msg.post('#', 'start_level')
end

---@package
---@param self level_maker.script
---@param message_id hash
---@param message table
---@param sender 'factory.level_maker'
function on_message(self, message_id, message, sender)
    if message_id == hash('start_level') then
        GameData.tilemap = create_tilemap(self)
        create_backgroud()
        create_pillar(self)
        create_reward_brick(self)
        create_flag(self)
    end
end