
-- 重力实现与反重力实现
-- 所需属性：重力、鸟对象的位置j、位置变化量（速率）、反重力方向（处理输入响应）
-- 所需方法：根据dt、重力、鸟自身位置等属性 进行位置递增的方法

local game_manager = require('main.game_manager')


local function dead(self)
    self.is_dead = true
    msg.post('/main_manager', 'score_state')
end

local function reset_game(self)
    go.set_position(self.start_pos)
    self.velocity = self.jump_force
end

local function clamp(n, min, max)
    return n < min and min or (n > max and max or n)
end


---@package
---@param self bird.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    msg.post('#sprite', 'disable')

    self.velocity = 0
    self.start_pos = go.get_position()
    self.jump_force = 380
    self.gravity = -980
    
    self.rot_factor = 0.015
    self.lerp_speed = 3
    self.is_dead = false
    self.is_hit_wall = false
    self.is_hit_pipe = false
    
    reset_game(self)
end

---@package
---@param self bird.script
---@param dt number
function update(self, dt)
    -- 如果处于标题开始状态
    if game_manager.game_state == 'title_state' then
        reset_game(self)
        msg.post('.', 'disable')
    end
    -- 如果处于开始倒数状态
    
    -- 如果处于游玩游戏状态
    if game_manager.game_state == 'play_state' then
        msg.post('.', 'enable')
        -- 重力值加速度
        self.velocity = self.velocity + self.gravity * dt

        -- 根据重力加速度更新鸟的位置
        local bird_pos = go.get_position()
        bird_pos.y = bird_pos.y + self.velocity * dt
        go.set_position(bird_pos)

        -- 根据重力加速度来表现旋转
        local target_angle = clamp(self.velocity * self.rot_factor, -1, 1)
        local taget_rotation = vmath.quat_rotation_z(target_angle)
        local current_rotation = go.get_rotation()
        local new_rotation = vmath.slerp(self.lerp_speed * dt, current_rotation, taget_rotation)
        go.set_rotation(new_rotation)
    end

    -- 如果处于结算游戏状态
    
    -- 调试模式
end

---@package
---@param self bird.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == hash('touch') or action_id == hash('fly') and action.pressed and
    game_manager.game_state == 'play_state' then
        self.velocity = self.jump_force    -- 飞行
    end

    -- if action_id == hash('reset') then
    --     reset_game(self)
    -- end
end

---@package
---@param self bird.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('trigger_response') then
        if message.group == hash('pipes') or message.group == hash('ground') then
            dead(self)
        end
    end

    if message_id == hash('trigger_response') and message.group == hash('get_score') and message.enter then
        local score = game_manager.get_player_score()
        local new_score = score + 1
        game_manager.set_player_score(new_score)
    end
end