
---- 重力实现与反重力实现 ----
---- 所需属性：重力、鸟对象的位置j、位置变化量（速率）、反重力方向（处理输入响应） ----
---- 所需方法：根据dt、重力、鸟自身位置等属性 进行位置递增的方法 ----


local function fly(self)
    self.velocity = self.jump_force
end

local function reset_game(self)
    go.set_position(self.start_pos)
    fly(self)
end


---@package
---@param self bird.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    self.velocity = 0
    self.start_pos = go.get_position()
    self.jump_force = 400
    self.gravity = -980
    
    -- 游戏体验 让玩家有反应时间 
    fly(self)
end

---@package
---@param self bird.script
---@param dt number
function update(self, dt)
    -- 重力值加速度
    self.velocity = self.velocity + self.gravity * dt
    -- 给鸟加上速度更新
    local bird_pos = go.get_position()
    bird_pos.y = bird_pos.y + self.velocity * dt
    go.set_position(bird_pos)

    -- 调试模式
end

---@package
---@param self bird.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == hash('touch') or action_id == hash('fly') and action.pressed then
        fly(self)
    end

    if action_id == hash('reset') then
        reset_game(self)
    end
end

---@package
---@param self bird.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('trigger_response') then
        print('you die!')
    end
end