local game_manager = require('main.game_manager')


local function play_game(self)
    gui.set_enabled(self.counter_node, false)
    gui.set_enabled(self.score_node, true)
    gui.set_enabled(self.pause_node, true)
    
    gui.set_text(self.score_node, self.score)
end

local function title_game(self)
    local text = 'Def-Flappy Brid~\nClick to start game~'
    gui.set_text(self.title_node, text)
    gui.set_enabled(self.title_node, true)
    gui.set_enabled(self.score_node, false)
    gui.set_enabled(self.pause_node, false)
    gui.set_enabled(self.counter_node, false)
    gui.set_enabled(self.final_text_node, false)
    gui.set_enabled(self.gold_score_node, false)
    gui.set_enabled(self.sliver_score_node, false)
    gui.set_enabled(self.bronze_score_node, false)
end

local function counter_game(self, dt)
    gui.set_enabled(self.title_node, false)
    gui.set_enabled(self.counter_node, true)

    self.counter = self.counter - dt * 2
    if self.counter <= 0 then
        msg.post('/main_manager', 'counter_end')
        self.counter = 4
    end
    gui.set_text(self.counter_node, tostring(string.format('%0d', self.counter)))
end

local function end_game(self)
    
end



local function pause_game(self)
    self.paused = not self.paused
    if self.paused then
        msg.post('main:/game_sceen_loader', 'set_time_step', { factor = 0, mode = 1 })
    else
        msg.post('main:/game_sceen_loader', 'set_time_step', { factor = 1, mode = 0 })
    end
end


---@package
---@param self game.gui_script
function init(self)
    msg.post('.', 'acquire_input_focus')
    self.score = game_manager.get_player_score()
    self.counter = 4
    self.score_node = gui.get_node('score')
    self.pause_node = gui.get_node('pause_button')
    self.title_node = gui.get_node('title')
    self.counter_node = gui.get_node('counter')
    self.final_text_node = gui.get_node('final_text')
    self.gold_score_node = gui.get_node('gold_score')
    self.sliver_score_node = gui.get_node('sliver_score')
    self.bronze_score_node = gui.get_node('bronze_score')

    self.paused = false
    title_game(self)
end

---@package
---@param self game.gui_script
---@param dt number
function update(self, dt)
    -- 如果处于标题开始状态
    if game_manager.game_state == 'title_state' then
        title_game(self)

    -- 如果处于开始倒数状态
    elseif game_manager.game_state == 'counter_state' then
        counter_game(self, dt)
    -- 如果处于游玩游戏状态
    elseif game_manager.game_state == 'play_state' then
        self.score = game_manager.get_player_score()
        gui.set_text(self.score_node, tostring(self.score))
    -- 如果处于结算游戏状态
    elseif game_manager.get_game_state() == 'score_state' then
        -- 结算奖牌奖励
        gui.set_enabled(self.final_text_node, true)
        local text = 'You die!\n Score: ' .. self.score
        gui.set_text(self.final_text_node, text)

        if self.score >= game_manager.gold_score then
            gui.set_enabled(self.gold_score_node, true)
            local text = 'Congratulation!\nYou got a Gold!'
            local node = gui.get_node('gold_text')
            gui.set_text(node, text)
        elseif self.score >= game_manager.sliver_score then
            gui.set_enabled(self.sliver_score_node, true)
            local text = 'Congratulation!\nYou got a Sliver!'
            local node = gui.get_node('sliver_text')
            gui.set_text(node, text)
        elseif self.score >= game_manager.bronze_score then
            gui.set_enabled(self.bronze_score_node, true)
            local text = 'Congratulation!\nYou got a Bronze!'
            local node = gui.get_node('bronze_text')
            gui.set_text(node, text)
        end
    end

    -- 调试模式
end

---@package
---@param self game.gui_script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('title_state') then
        title_game(self)
    elseif message_id == hash('play_state') then
        play_game(self)
    elseif message_id == hash('score_state') then

    end

    if message_id == hash('add_score') then
        self.score = self.score + message.score
        gui.set_text(self.score_node, tostring(self.score))
    end
end

---@package
---@param self game.gui_script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == hash('left_click') and action.pressed and
    gui.pick_node(self.pause_node, action.x, action.y) then
        pause_game(self)
    end
end