components {
  id: "pipe_script"
  component: "/main/pipe.script"
}
embedded_components {
  id: "pipe_bottom"
  type: "sprite"
  data: "default_animation: \"pipe\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  y: 149.0\n"
  "  w: 34.0\n"
  "}\n"
  "size {\n"
  "  x: 121.0\n"
  "  y: 600.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/arts.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "pipe_top"
  type: "sprite"
  data: "default_animation: \"pipe\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  y: 149.0\n"
  "  w: 34.0\n"
  "}\n"
  "size {\n"
  "  x: 121.0\n"
  "  y: 600.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/arts.atlas\"\n"
  "}\n"
  ""
  position {
    y: 792.0
  }
  rotation {
    z: 1.0
    w: 6.123234E-17
  }
}
embedded_components {
  id: "score_scope"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"get_score\"\n"
  "mask: \"bird\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 55.0\n"
  "      y: 397.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 10.0\n"
  "  data: 103.39529\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"pipes\"\n"
  "mask: \"bird\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 793.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"top\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"bottom\"\n"
  "  }\n"
  "  data: 43.551903\n"
  "  data: 295.1761\n"
  "  data: 10.0\n"
  "  data: 43.551903\n"
  "  data: 294.0282\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
