-- 管道生成工厂
-- 疑问：工厂如何生效？如何生成在想要的位置上？渲染z轴有影响吗

-- 管道生成所需的属性和方法
-- 属性：上下管道的间隙，管道对之间的间隔
-- 计时器

-- 有了中心点位置，就有离这个中心点最小与最大值的offset偏移值
-- 追踪生成的实例，拿到上一个实例的y轴位置的参数

local game_manager = require('main.game_manager')

local spawn_time = 2.5
local component = '#pipes_factory'
local gap = 0
local spawn_x = SCREEN_WIDTH + 60
local center_y = SCREEN_HEIGHT / 2


local function spawn_pipe(self)
	local pos = go.get_position()
	pos = vmath.vector3(spawn_x, math.random(-self.pipe_gap, self.pipe_gap), 0)
	local id = factory.create(component, pos, nil, { scored = false })
	table.insert(self.spawn_pipes, id)
end

local function compute_pipes_gap(self)
	
end

---@package
---@param self pipe_factory.script
function init(self)
	math.random(os.time())

	self.timer = 0
	self.spawn_pipes = {}
	self.pipe_gap = 80
end

---@package
---@param self pipes_factory.script
---@param dt number
function update(self, dt)
	-- 如果处于标题开始状态
	if game_manager.game_state == 'play_state' then
		self.timer = self.timer + dt
		if self.timer >= spawn_time then
			spawn_pipe(self)
			self.timer = 0
		end
	end
	-- 如果处于开始倒数状态
	-- 如果处于游玩游戏状态
	-- 如果处于结算游戏状态

end