local input = require('core.systems.input')

go.property('move_speed', 200)

local GRAVITY = -980

---@package
---@param self player.script
function init(self)
	-- 增加重力
	self.velocity = vmath.vector3()
	self.direction = vmath.vector3(-1, 0, 0)
	self.correction = vmath.vector3()
	-- self.speed 已由编辑器注入
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
	if math.abs(self.direction.x) > 0 then
		-- self.velocity.x = self.move_speed * self.direction.x
	else
		self.velocity.x = 0
	end

	self.velocity.y = self.velocity.y + GRAVITY * dt

	local pos = go.get_position()

	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)

	self.correction = vmath.vector3()
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	if message_id == hash('contact_point_response') then
		if message.group == hash('ground') or message.group == hash('pillars') then
			handle_projection(self, message.normal, message.distance)
		end

		if message.group == hash('pillars') then
			self.direction.x = -self.direction.x
			sprite.set_hflip(go.get_id(), true)
		end
	end

	if message_id == hash('enemy_dead') then
		go.delete()
	end
end
