local input = require('core.systems.input')

go.property('move_speed', 200)

local GRAVITY = -980

---@package
---@param self player.script
function init(self)
	-- 增加重力
	self.velocity = vmath.vector3()
	self.direction = vmath.vector3(-1, 0, 0)
	self.correction = vmath.vector3()
	-- self.speed 已由编辑器注入
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
	if math.abs(self.direction.x) > 0 then
		-- self.velocity.x = self.move_speed * self.direction.x
	else
		self.velocity.x = 0
	end

	self.velocity.y = self.velocity.y + GRAVITY * dt

	local pos = go.get_position()

	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)

	self.correction = vmath.vector3()
end

local function handle_projection(self, normal, distance)
	if distance < 0.00001 then return end

	-- 将当前积累的修正向量投影到法线上
	local proj = vmath.project(self.correction, normal * distance)
	if proj < 1 then
		-- 计算需要把角色“推”出来多少距离
		local comp = (distance - distance * proj) * normal
		go.set_position(go.get_position() + comp)
		self.correction = self.correction + comp

		-- 判断是否撞到了地面 (法线向上)
		if normal.y > 0.7 then
			self.on_ground = true
			self.velocity.y = 0 -- 落地时消除垂直速度
		end

		-- 判断是否撞到了天花板 (法线向下)
		if normal.y < -0.7 then self.velocity.y = 0 end
	end
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	if message_id == hash('contact_point_response') then
		if message.group == hash('ground') or message.group == hash('pillars') then
			handle_projection(self, message.normal, message.distance)
		end

		if message.group == hash('pillars') then
			self.direction.x = -self.direction.x
			sprite.set_hflip(go.get_id(), true)
		end
	end

	if message_id == hash('enemy_dead') then
		go.delete()
	end
end

