local druid = require("druid.druid")
local monarch = require "monarch.monarch"
local wild_menu = require('ui.widgets.selection_menu.selection_menu')

function init(self)
    msg.post('.', 'acquire_input_focus')
    self.druid = druid.new(self)
    self.druid:new_widget(wild_menu)

end

function final(self)
    self.druid:final()
end

function update(self, dt)
    self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
    self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id == hash('back') then
        monarch.back()
    end
    return self.druid:on_input(action_id, action)
end
