



function init(self)
	msg.post('.', 'acquire_input_focus')
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.angle = 0
	self.is_rotate = false
end

function update(self, dt)
	if self.input.x == -1 then
		self.angle = self.angle + 45 * dt
	elseif self.input.x == 1 then
		self.angle = self.angle - 45 * dt
	end
	local rad_angle = math.rad(self.angle)
	
	go.set_rotation(vmath.quat_rotation_z(rad_angle))
	self.input = vmath.vector3()
end

function on_input(self, action_id, action)
	if action_id == hash('left') then
		self.input.x = -1
	elseif action_id == hash('right') then
		self.input.x = 1
	end
end

function on_message(self, message_id, message)
	if message_id == hash('shoot') then
		shoot(self, message)
	end
end