SCREEN_WIDTH = sys.get_config_number('display.width')
SCREEN_HEIGHT = sys.get_config_number('display.height')



function normalize_delta(delta)
	-- 归一化角差到 [-pi, pi]
	if delta > math.pi then
		delta = delta - 2 * math.pi
	elseif delta < -math.pi then
		delta = delta + 2 * math.pi
	end
	return delta
end



function init(self)
	particlefx.play('background#bg_fx')
	print(SCREEN_WIDTH, SCREEN_HEIGHT)
end