

local function shoot(self)
	local pos = go.get_position()         -- world position
	local rot = go.get_rotation()

	for _, local_offset in ipairs(self.fire_points) do
		-- 把局部向量旋转到世界空间 --
		local world_offset = vmath.rotate(rot, local_offset)
		-- 算出激光生成点并创建激光，带上相同的 rotation 使其朝向一致 --
		local spawn_pos = pos + world_offset

		-- 计算朝向（单位向量）
		local direction = vmath.normalize(world_offset)
		local angle = math.atan2(direction.y, direction.x)
		local spawn_rot = vmath.quat_rotation_z(angle)

		factory.create('/ship#factory_laser', spawn_pos, spawn_rot, {
			speed = 1000,
			direction = direction
		})
	end		
end

function init(self)
	msg.post(".", "acquire_input_focus")
	for i = 1, 3 do
		msg.post('#effect_spr_' .. i, 'disable')
	end
	
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.move_speed = 30
	self.acceleration_rate = 1.13
	self.max_move_speed = 60
	self.rot_speed = math.pi / 20
	self.position = go.get_position()
	self.target_pos = self.position
	self.current_angle = 0
	self.target_angle = self.current_angle
	
	self.state = 'idle'
	self.engine_on = false
	self.autofire_timer = 0.1
	self.fire_points = {
		vmath.vector3(0, 80, 0),
		vmath.vector3(80, 80, 0),
		vmath.vector3(-80, 80, 0),
		vmath.vector3(0, -80, 0),
		vmath.vector3(80, -80, 0),
		vmath.vector3(-80, -80, 0),
	}
end

local function engine_on(self)
	if self.engine_on then
		for i = 1, 3 do
			msg.post('#effect_spr_' .. i, 'enable')
		end
	else
		for i = 1, 3 do
			msg.post('#effect_spr_' .. i, 'disable')
		end
	end
end

function update(self, dt)
	if self.state == 'rotating' then
		local delta = self.target_angle - self.current_angle

		delta = normalize_delta(delta)

		if math.abs(delta) < self.rot_speed * dt then
			self.current_angle = self.target_angle
			self.state = 'moving'
		else
			self.current_angle = self.current_angle + (delta > 0 and 1 or -1) * self.rot_speed * dt
		end
		go.set_rotation(vmath.quat_rotation_z(self.current_angle))
	end
	
	if self.state == 'moving' then
		local distance_vec = self.target_pos - self.position
		local distance_len = vmath.length(distance_vec)
		self.direction = vmath.normalize(distance_vec)

		if distance_len <= self.max_move_speed then
			self.position = self.position - self.direction * (self.max_move_speed / 2) * dt
		end
		
		if distance_len < self.move_speed * dt then
			self.position = self.target_pos
			self.state = "idle"
			self.engine_on = false
		else
			self.move_speed = self.move_speed + self.move_speed * self.acceleration_rate * dt
			if self.move_speed >= self.max_move_speed then
				self.move_speed = self.max_move_speed
			end
			self.position = self.position + self.direction * self.move_speed * dt
		end
		go.set_position(self.position)
	end

	engine_on(self)

	self.autofire_timer = self.autofire_timer - dt
	if self.autofire_timer <= 0 then
		shoot(self)
		self.autofire_timer = 0.2
	end
end

function on_input(self, action_id, action)
	if action_id == hash('touch') and action.pressed then
		self.engine_on = true
		self.target_pos = vmath.vector3(action.x, action.y, 0)
		self.target_angle = math.atan2(self.target_pos.y - self.position.y, self.target_pos.x - self.position.x)
		self.state = 'rotating'
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash('collision_response') and message.group == hash('asteroid')then
		print('attack range!')
	end
end