local SoundController = require('core.components.sound_controller')
local Input = require('core.systems.input')


local TILE_SIZE = 32 * 3


---@package
---@param self player.script
function init(self)
	msg.post('.', 'acquire_input_focus')

	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.player_grid_x = 0
	self.player_grid_y = 0
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)

end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)

end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)

end

