local input = require('core.systems.input')
local game_data = require('data.config.game_data')
local SoundController = require('core.components.sound_controller')
local machine = require('lib.thirdparty.statemachine')

go.property('move_speed', 400)

local GRAVITY = -980

-- [优化1] 预定义变量Hash
local ANIMS = {
    IDLE = hash('idle'),
    RUN = hash('run'),
    JUMP = hash('jump'),
    HURT = hash('hurt'),
}

---@package
---@param self player.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    self.current_anim = 'idle'
    self.inital_pos = go.get_position()
    -- 增加重力
    self.velocity = vmath.vector3()
    self.jump_force = 700
    self.direction = vmath.vector3()
    self.input = vmath.vector3()
    self.correction = vmath.vector3()
    -- self.speed 已由编辑器注入
    self.is_moving = false
    self.on_ground = false
    self.hp = 3

    -- 引入状态机，初始化状态机
    -- 利用callback自动处理动画
    self.fsm = machine.create({
        initial = "idle",
        events = {
            { name = 'move',     from = {'idle', 'jumping'},    to = 'running' },
            { name = 'stop',     from = {'running', 'jumping'}, to = 'idle'    },
            { name = 'jump',     from = { 'idle', 'running' },  to = 'jumping' },
            { name = 'land',     from = 'jumping',                 to = 'idle'    },
            { name = 'get_hurt', from = "*",                    to = 'hurt'    },
            { name = 'recover',  from = 'hurt',                 to = 'idle'    },
        },
        callbacks = {
            onenteridle =    function () sprite.play_flipbook('#sprite', ANIMS.IDLE) end,
            onenterrunning = function () sprite.play_flipbook('#sprite', ANIMS.RUN) end,
            onenterjumping = function () sprite.play_flipbook('#sprite', ANIMS.JUMP) end,
            onenterhurt =    function (fsm, event, from, to)
                sprite.play_flipbook('#sprite', ANIMS.HURT)
                timer.delay(0.3, false, function()
                    fsm:recover()
                end)
            end,
            onstatechange = function(fsm, event, from, to)
                print("[FSM] " .. from .. " -> " .. to .. " [" .. event .. "]")
            end
        }

    })
end

---{ 'idle', 'runing' }ckage
---@param self player.script
---@param dt number
function update(self, dt)
    -- A. 物理计算 (始终执行)
    self.velocity.y = self.velocity.y + GRAVITY * dt
    
    -- 硬直时间
    if self.fsm:is('hurt') then
        self.velocity.x = 0
    elseif self.fsm:is('jumping') then
        self.velocity.x = self.move_speed * self.direction.x
    else
        -- 地面状态 (idle / running)
        self.velocity.x = self.move_speed * self.direction.x
        -- [优化2] 简化状态切换逻辑
        if self.direction.x ~= 0 and self.fsm.current ~= 'running' then
            self.fsm:move()
        elseif self.direction.x == 0 and self.fsm.current ~= 'idle' then
            self.fsm:stop()
        end
    end

    -- C. 视觉表现 (Visuals)
    -- [优化3]翻转逻辑放在 update，根据实际速度方向决定，而不是按键
    if self.velocity.x > 0 then
        sprite.set_hflip('#sprite', false)
    elseif self.velocity.x < 0 then
        sprite.set_hflip('#sprite', true)
    end

    -- D. 边界与生命值检查
    local pos = go.get_position()
    if pos.y <= -100 then
        self.hp = self.hp - 1
        go.set_position(self.inital_pos)
        self.velocity = vmath.vector3()

        if self.fsm:can('stop') then self.fsm:stop() end
    end

    if self.hp <= 0 then
        msg.post('/level_manager', 'player_dead')
    end

    -- E. 应用移动
    local pos = go.get_position()
    pos = pos + self.velocity * dt
    go.set_position(pos)

    -- E. 清理本帧输入
    self.input = vmath.vector3()
    self.correction = vmath.vector3()
    self.direction = vmath.vector3()
    self.on_ground = false
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('contact_point_response') then
        if message.group == hash('ground') or message.group == hash('pillars') or message.group == hash('bricks')then
            handle_projection(self, message.normal, message.distance)
        elseif message.group == hash('enemies') then
            handle_bounced(self, message.normal, message.distance, message.other_id)
        end
    end

    if message_id == hash('trigger_response') then
        if message.group == hash('flag') and message.enter then
            msg.post('/level_manager', 'level_clear')
        elseif message.group == hash('rewards') then
            msg.post('/monarch#level_1', 'add_score')
        elseif message.group == hash('keys') then
            print('lock opened!')
        end
    end
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    -- 如果处于受伤状态，忽略所有输入
    if self.fsm:is('hurt') then return end

    if action_id == input.LEFT then
        self.input.x = -1
    elseif action_id == input.RIGHT then
        self.input.x = 1
    end

    -- 跳跃逻辑: 双重检测 通过状态机和状态变量
    if action_id == input.JUMP and action.pressed then
        if self.fsm:can('jump') and self.on_ground then
            self.velocity.y = self.jump_force
            self.fsm:jump()
            -- SoundController.play('sfx_jump', SoundController.GROUP_SFX)
        end
    end

    if vmath.length(self.input) > 0 then
        self.direction = vmath.normalize(self.input)
    end
end

-- --- 这是一个标准的碰撞分离函数 (Defold 圣经) ---
function handle_projection(self, normal, distance)
    if distance < 0.00001 then return end

    -- 将当前积累的修正向量投影到法线上
    local proj = vmath.project(self.correction, normal * distance)
    if proj < 1 then
        -- 计算需要把角色“推”出来多少距离
        local comp = (distance - distance * proj) * normal
        go.set_position(go.get_position() + comp)
        self.correction = self.correction + comp
        
        -- 判断是否撞到了地面 (法线向上)
        if normal.y > 0.7 then
            self.on_ground = true
            self.velocity.y = 0 -- 落地时消除垂直速度

            -- 落地逻辑：如果我们还在jumping状态，说明刚落地
            if self.fsm:is('jumping') and self.fsm:can('land') then
                self.fsm:land()
            end
        end
        
        -- 判断是否撞到了天花板 (法线向下)
        if normal.y < -0.7 then self.velocity.y = 0 end
    end
end

function handle_bounced(self, normal, distance, id)
    if normal.y > 0.5 then
        self.velocity.y = self.jump_force * 0.75
        msg.post(id, 'enemy_dead')
        if self.fsm:can('jump') then self.fsm:jump() end
    elseif normal.y <= 0.5 then
        --受伤逻辑
        if self.fsm:can('get_hurt') then
            self.fsm:get_hurt()

            -- 物理击退
            self.velocity.x = normal.x * 400
            self.velocity.y = 200

            -- 扣血
            self.hp = self.hp - 1
        end
    end
    -- local bounce_force = 100
    -- local pos = go.get_position()
    -- local bounced_pos = pos + bounce_force * normal
    -- go.animate(go.get_id(), 'position', go.PLAYBACK_ONCE_FORWARD, bounced_pos, go.EASING_OUTBACK, 0.5)

    -- msg.post("@system:", "set_time_step", { factor = 0, mode = 1 })
    -- timer.delay(0.05, false, function()
    --     msg.post("@system:", "set_time_step", { factor = 1, mode = 1 })
    -- end)
end

