local input = require('core.systems.input')

go.property('move_speed', 400)

local GRAVITY = -980

local function update_animation(self)
    local anim = 'idle'
    if self.is_moving then
        anim = 'walk'
    -- elseif not self.on_ground then
    --     anim = 'jump'
    else
        anim = 'idle'
    end

    if anim ~= self.current_anim then
        sprite.play_flipbook('#sprite', anim)
        self.current_anim = anim
    end
end

---@package
---@param self player.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    self.current_anim = 'idle'
    -- 增加重力
    self.velocity = vmath.vector3()
    self.jump_force = 700
    self.direction = vmath.vector3()
    self.input = vmath.vector3()
    self.correction = vmath.vector3()
    -- self.speed 已由编辑器注入
    self.is_moving = false
    self.on_ground = false

    self.hp = 3
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
    self.velocity.y = self.velocity.y + GRAVITY * dt
    
    local pos = go.get_position()
    if self.is_moving then
        self.velocity.x = self.move_speed * self.direction.x
    else
        self.velocity.x = 0
    end

    local pos = go.get_position()
    pos = pos + self.velocity * dt
    go.set_position(pos)

    update_animation(self)

    self.input = vmath.vector3()
    self.correction = vmath.vector3()
    self.is_moving = false
    self.on_ground = false
end

---@package
---@param self player.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('contact_point_response') then
        if message.group == hash('ground') or message.group == hash('pillars') or message.group == hash('bricks')then
            handle_projection(self, message.normal, message.distance)
        elseif message.group == hash('enemies')  then
            self.hp = self.hp - 1
            if self.hp <= 0 then
                msg.post('/level_manager', 'player_dead')
            end
            print('hurt!')
        end
    end
    

    if message_id == hash('trigger_response') then
        if message.group == hash('flag') then
            msg.post('/level_manager', 'level_clear')
        elseif message.group == hash('reward') then
            msg.post('/monarch#level_1', 'add_score')
        elseif message.group == hash('keys') then
            print('lock opened!')
            
        end
    end
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == input.LEFT then
        self.input.x = -1
        sprite.set_hflip('/player/player#sprite', true)
    elseif action_id == input.RIGHT then
        self.input.x = 1
        sprite.set_hflip('/player/player#sprite', false)
    end

    if action_id == input.JUMP and action.pressed and self.on_ground then
        self.velocity.y = self.jump_force
    end

    if vmath.length(self.input) > 0 then
        self.is_moving = true
        self.direction = vmath.normalize(self.input)
    end
end

-- --- 这是一个标准的碰撞分离函数 (Defold 圣经) ---
function handle_projection(self, normal, distance)
    if distance < 0.00001 then
        return
    end

    -- 将当前积累的修正向量投影到法线上
    local proj = vmath.project(self.correction, normal * distance)
    if proj < 1 then
        -- 计算需要把角色“推”出来多少距离
        local comp = (distance - distance * proj) * normal
        go.set_position(go.get_position() + comp)
        self.correction = self.correction + comp
        
        -- 判断是否撞到了地面 (法线向上)
        if normal.y > 0.7 then
            self.on_ground = true
            self.velocity.y = 0 -- 落地时消除垂直速度
        end
        
        -- 判断是否撞到了天花板 (法线向下)
        if normal.y < -0.7 then
            self.velocity.y = 0
        end
    end
end

