local monarch = require "monarch.monarch"
local transitions = require('monarch.transitions.gui')

function init(self)
    msg.post(".", "acquire_input_focus")
    local transition = transitions.create(gui.get_node('root'))
        .show_in(transitions.slide_in_right, gui.EASING_OUTQUAD, 0.4, 0)  -- 进入：从右滑入，耗时0.4秒
        .show_out(transitions.slide_out_left, gui.EASING_INQUAD, 0.4, 0)  -- 退出：向左滑出，耗时0.4秒
        .back_in(transitions.slide_in_left, gui.EASING_OUTQUAD, 0.4, 0)   -- 返回：(如果从下一级返回) 从左滑入
        .back_out(transitions.slide_out_right, gui.EASING_INQUAD, 0.4, 0) -- 返回退出：向右滑出
    monarch.on_transition('main_menu', transition)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    monarch.on_message(message_id, message, sender)
    if message_id == monarch.TRANSITION.DONE and message.transition == monarch.TRANSITION.SHOW_IN then
        print("Show in done!")
    end
end

function on_input(self, action_id, action)
    if action_id == hash('touch') and action.pressed then
        monarch.show('level')
    end
end

function on_reload(self)
end

