SCREEN_WIDTH = sys.get_config_number('display.width')
SCREEN_HEIGHT = sys.get_config_number('display.height')

local game_manager = require('game.managers.game_manager')

local function load_main_menu(self)
    msg.post('#main_menu', 'load')
end

local function unload_main_menu(self)
    msg.post('#main_menu', 'unload')
end

local  function load_select_scene(self)
    msg.post('#select_scene', 'load')
end

local  function unload_select_scene(self)
    msg.post('#select_scene', 'unload')
end

local function load_level(self)
    msg.post('#level', 'load')
end

local function unload_level(self)
    msg.post('#level', 'unload')
end


---@package
---@param self main.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    load_main_menu(self)
end

---@package
---@param self main.script
---@param dt number
function update(self, dt)
    if game_manager.get_state() == 'title_state' then
        print('title_state')
    elseif game_manager.get_state() == 'select_state' then
        print('select_state')
    elseif game_manager.get_state() == 'serve_state' then
        print('serve_state')
    elseif game_manager.get_state() == 'play_state' then
        print('serve_state')
    elseif game_manager.get_state() == 'score_state' then
        print('score_state')
    end
end

---@package
---@param self main.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('goto_select_scene') then
        unload_main_menu(self)
        load_select_scene(self)
    elseif message_id == hash('goto_level') then
        unload_select_scene(self)
        load_level(self)
    elseif message_id == hash('proxy_loaded') then
        msg.post(sender, 'init')
        msg.post(sender, 'enable')
    end
end

function final(self)
    msg.post(".", "release_input_focus")
end
