---@package
---@param self cursor_script.script
function init(self)
	print("Hello Defold! I am alive!")
	msg.post('.', 'acquire_input_focus')
end

---@package
---@param self cursor_script.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	local mouse_pos = vmath.vector3(action.x, action.y, 0)
	go.set_position(mouse_pos)
end