------------- 设计与实现 -------------
--[[
设计意图：
- 通过在网格上逐格移动的光标来在环境中移动，同时显示当前单元格在游戏中的坐标。

实现步骤：- 功能 - 实现步骤
- （最简易的开始）把获取的鼠标位置更新应用至光标对象，并使用defos关闭系统鼠标显示。
- 实现世界空间坐标与瓦片地图坐标的相互转换，从世界空间坐标到瓦片地图坐标，再从瓦片地图坐标到世界空间坐标。
	- 使用utilites-常用公共工具箱-utils，即defold中lua module来作为可复用模块。
- 把转换的值的位置更新应用至光标对象。

知识点：
- 明确关于屏幕空间坐标、世界空间坐标、局部空间坐标、瓦片地图坐标等概念
- 世界空间坐标 与 瓦片地图坐标 的相互转换的数学原理：除法与乘法
	- 世界 --> 瓦片：世界位置 / 单个瓦片尺寸（向上/向下取整）lua是从1-based开始索引（瓦片地图Tile为1开始而不是0），因此一般使用向上取整（弥补0的缺失）
	- 瓦片 --> 世界：单个瓦片尺寸 * 世界位置 - 单个瓦片尺寸 / 2（从右上角为锚点切换成中心点锚点）
]]--
-------------------------------------

local utils = require('main.utils')

---- 关于map组件的url（方便复用） ----
local MAP = '/map#map_farm'

---- 边界检测函数：需要检测瓦片是否在瓦片地图边界之内 ----
	---- 所需的Defold API：tilemap.get_bounds() ----
local function within_bounds(position)
	local tile = utils.world_to_tile(position)
	local bx, by, bw, bh = tilemap.get_bounds(MAP)
	return 
	tile.x >= bx and 
	tile.y >= by and 
	tile.x < (bx + bw) and 
	tile.y < (by + bh)
end

local function update_label_coordinate(cell_coordinate)
	local text = "X: " .. tostring(cell_coordinate.x) .. ", Y: " .. tostring(cell_coordinate.y)
	label.set_text('label_coordinate#label', text)
end

local function smooth_switch(position)
	go.cancel_animations(".", "position")
	go.animate('.', 'position', go.PLAYBACK_ONCE_FORWARD, position, go.EASING_OUTQUAD, 0.1)
	go.cancel_animations(".", "scale")
	go.animate('.', 'scale', go.PLAYBACK_ONCE_FORWARD, 2.3, go.EASING_OUTQUAD, 0.2, 0, function() 
		go.animate('.', 'scale', go.PLAYBACK_ONCE_FORWARD, 2, go.EASING_OUTQUAD, 0.1)
	end)
end

local function move_cursor_cell(position)	
	local cursor_cell = utils.world_to_tile(position)
	local cursor_pos = utils.tile_to_world(cursor_cell)
	cursor_pos.z = 1
	
	-- go.set_position(cursor_pos)
	smooth_switch(cursor_pos)    -- 优化表现：从卡顿一帧切换到有过渡的动画效果切换 --
	
	update_label_coordinate(cursor_cell)
end

function init(self)
	msg.post('.', 'acquire_input_focus')
end

function update(self, dt)

end

function on_input(self, action_id, action)    				-- 如果没有其他输入，on_input会自动获取鼠标坐标，即action的坐标 --
	local mouse_pos = vmath.vector3(action.x, action.y, 1)  	-- 创建获取得到的鼠标坐标的变量 --
	if action.x and action.y then    							-- 判断有无鼠标坐标 --
		if within_bounds(mouse_pos) then    						-- 判断是否在边界之内：无法超出边界 --
			-- go.set_position(mouse_pos)
			move_cursor_cell(mouse_pos)
		end
	end
end