local function load_level()
    msg.post('/game_scene_loader#level', 'load')
end

local function unload_level()
    msg.post('/game_scene_loader#level', 'unload')
end


---@package
---@param self main.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    load_level()
end

---@package
---@param self main.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('proxy_loaded') then
        msg.post(sender, 'init')
        msg.post(sender, 'enable')
    end
end