local monarch = require ("monarch.monarch")
local game_data = require('data.config.game_data')

function init(self)
    msg.post(".", "acquire_input_focus")
    self.score = game_data.get_score()
    self.score_node = gui.get_node('score')
    gui.set_text(self.score_node, self.score)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash('add_score') then
        self.score = self.score + 500
        gui.set_text(self.score_node, self.score)
        game_data.set_score(self.score)
    end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
