--[[

1. 球的初始随机方向
2. 球的飞行速度
3. 球与墙壁的碰撞反弹
4. 球与球拍的碰撞反弹
5. 球过界的计分

]]--

local sceen_w, sceen_h = 960, 640

local function setup_ball(self)
	local direction = vmath.vector3() 
	direction.x = math.random(0, 1) == 0 and -1 or 1
	direction.y = math.random(-150, 150) / 100

	self.dir = vmath.normalize(direction)
	self.speed = 400.0
	self.velocity = self.dir * self.speed

	self.increase_factor = 1.13
end

local function reset_ball(self)
	local pos = go.get_position()
	pos.x, pos.y = sceen_w /2, sceen_h / 2
	go.set_position(pos)
	setup_ball(self)
end

function init(self)
	msg.post('.', 'acquire_input_focus')
	reset_ball(self)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove thiss function if not needed
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)
	
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash('collision_response') then
		if message.group == hash('paddles') then
			local pos = go.get_position()
			if pos.x < sceen_w / 2 then
				pos.x = pos.x + 10
			else
				pos.x = pos.x - 10
			end
			go.set_position(pos)
			self.velocity.x = -self.velocity.x
			self.velocity.y = math.random(-150, 300)
			self.speed = self.speed * self.increase_factor
			print('paddle boom!')
		elseif message.group == hash('wall_up') or message.group == hash('wall_down') then
			self.velocity.y = -self.velocity.y
			self.speed = self.speed * self.increase_factor
			print('wall boom!')
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash('restart') then
		reset_ball(self)
	end
end

function on_reload(self)
	go.property("speed", 400)
end
