function init(self)
	self.score_p1 = 0
	self.score_p2 = 0
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash('update_score_p2') then
		self.score_p2 = self.score_p2 + message.score_p2
		local score_node = gui.get_node('score_p2')
		gui.set_text(score_node, self.score_p2)
	elseif message_id == hash('update_score_p1') then
		self.score_p1 = self.score_p1 + message.score_p1
		local score_node = gui.get_node('score_p1')
		gui.set_text(score_node, self.score_p1)
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
