components {
  id: "paddle"
  component: "/main/paddle.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"paddle\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/art_src.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"paddles\"\n"
  "mask: \"balls\"\n"
  "mask: \"wall_up\"\n"
  "mask: \"wall_down\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -2.0\n"
  "      y: -2.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 48.394627\n"
  "  data: 117.35496\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "sfx_move"
  type: "sound"
  data: "sound: \"/assets/sfxs/move.ogg\"\n"
  "looping: 1\n"
  ""
}
