local sceen_h = tonumber(sys.get_config("display.height"))

function init(self)
	msg.post('.', 'acquire_input_focus')

	-- msg.post('@system:', 'toggle_physics_debug')
	
	self.moving = false
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.speed = 350
end

function final(self)

end

function update(self, dt)
	if self.moving then
		local position = go.get_position()
		position = position + self.direction * self.speed * dt
		go.set_position(position)
	end

	-- self.input.x = 0
	self.input.y = 0
	self.moving = false
end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash('collision_response') then
		if message.group == hash('wall_up') or message.group == hash('wall_down') then
			local pos = go.get_position()
			local paddle_h = go.get('#sprite', 'size.y') * 0.5 - 5
			local min_y = 0 + paddle_h / 2
			local max_y = sceen_h - paddle_h / 2
			-- pos.y = math.max(min_y, math.min(pos.y, max_y))
			pos.y = vmath.clamp(pos.y, min_y, max_y)
			go.set_position(pos)
			print('Wall!')
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash('player_up') then
		self.input.y = 1
	elseif action_id == hash('player_down') then
		self.input.y = -1
	end

	if vmath.length(self.input) > 0 then
		self.moving = true
		self.direction = vmath.normalize(self.input)
	end
end

function on_reload(self)

end
