function init(self)
	msg.post('.', 'acquire_input_focus')
	self.moving = false
	self.input = vmath.vector3()
	self.direction = vmath.vector3()
	self.speed = 200
end

function final(self)

end

function update(self, dt)
	if self.moving then
		local position = go.get_position()
		position = position + self.direction * self.speed * dt
		go.set_position(position)
	end

	-- self.input.x = 0
	self.input.y = 0
	self.moving = false
end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash('collision_response') then
		if 
	end
end

function on_input(self, action_id, action)
	if action_id == hash('player_up') then
		self.input.y = 1
	elseif action_id == hash('player_down') then
		self.input.y = -1
	end

	if vmath.length(self.input) > 0 then
		self.moving = true
		self.direction = self.input
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
