local init_pos = vmath.vector3(138, -138, 0)
local end_pos = vmath.vector3(138, 140, 0)


function init(self)
	self.dialog_node = gui.get_node('dialog_box')
	gui.set_position(self.dialog_node, init_pos)
	self.is_show = false
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	
end

function dialog_show(self)
	if self.is_show then 
		gui.animate(self.dialog_node, gui.PROP_POSITION, init_pos, gui.EASING_OUTCUBIC, 0.8)
		self.is_show = false
	else
		self.is_show = true
		gui.animate(self.dialog_node, gui.PROP_POSITION, end_pos, gui.EASING_OUTCUBIC, 0.8)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash('dialog_start') then
		dialog_show(self)
	end
end

function on_input(self, action_id, action)
	
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
