local monarch = require "monarch.monarch"
local transitions = require('monarch.transitions.gui')

function init(self)
    msg.post(".", "acquire_input_focus")

    local transition = transitions.create(gui.get_node('root'))
        .show_in(transitions.fade_in, gui.EASING_OUTQUAD, 0.4, 0)
        .show_out(transitions.fade_out, gui.EASING_INQUAD, 0.6, 0)
    monarch.on_transition('select_menu', transition)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    monarch.on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    if action_id == hash('start') then
        gui.set_enabled(gui.get_node('bg'), true)
        monarch.show('level_2', { sequential = true })
    end
end

function on_reload(self)
end
