--[[ 
三个问题
1. 怎么样才能移动
2. 怎么才能转向
3. 怎么停止
]]--

SCREEN_WIDTH = sys.get_config_number('display.width')
SCREEN_HEIGHT = sys.get_config_number('display.height')

go.property('rotate_speed', 180)

local function wrap_position(position)
	position.x = position.x % SCREEN_WIDTH
	position.y = position.y % SCREEN_HEIGHT
	return position
end

local function set_engine(self, enable)
	if enable == true and self.engine_on == false then
		self.engine_on = true
		msg.post('#effect_spr', 'enable')
	elseif enable == false and self.engine_on == true then
		self.engine_on = false
		msg.post('#effect_spr', 'disable')
	end
end


local function shoot(self)
	local pos = go.get_position()
	local size_sprite = go.get('#ship_spr', 'size')

	local pos_laser = vmath.vector3()
	local distance = size_sprite.y / 3
	local angle_rad = math.rad(self.angle)

	pos_laser.x = pos.x + distance * math.cos(angle_rad)
	pos_laser.y = pos.y + distance * math.sin(angle_rad)

	local direction = vmath.vector3()
	direction.x = math.cos(angle_rad)
	direction.y = math.sin(angle_rad)
	local rot = vmath.quat_rotation_z(angle_rad)

	local props = { speed = 1000, direction = direction}
	
	factory.create('#laser_factory', pos_laser, rot, props)
end

function init(self)
	msg.post('.', 'acquire_input_focus')
	msg.post('#effect_spr', 'disable')
	self.input = vmath.vector3()
	self.angle = 0
	self.speed = 0
	self.max_acceleration = 600
	self.velocity = vmath.vector3()
	self.engine_on = false
end

function update(self, dt)
	-- 旋转 --
	if self.input.x == 1 then
		self.angle = self.angle + self.rotate_speed * dt
	elseif self.input.x == -1 then
		self.angle = self.angle - self.rotate_speed * dt
	end
	local angle_rad = math.rad(self.angle)
	local rotation = vmath.quat_rotation_z(angle_rad)
	go.set_rotation(rotation)

	-- 方向和角度 --
	local direction = vmath.vector3()
	direction.x = math.cos(angle_rad)
	direction.y = math.sin(angle_rad)
	self.velocity = direction * self.speed

	if self.input.y == 1 then
		self.speed = self.speed + self.max_acceleration * dt
		set_engine(self, true)
	elseif self.speed > 0 then
		self.speed = self.speed - (self.max_acceleration / 2) * dt
		set_engine(self, false)
	end
	self.speed = vmath.clamp(self.speed, 0, self.max_acceleration)

	local pos = go.get_position()
	pos = pos + self.velocity * dt
	pos = wrap_position(pos)
	go.set_position(pos)
	

	self.input = vmath.vector3()
end

function on_input(self, action_id, action)
	if action_id == hash('up') then
		self.input.y = 1
	elseif action_id == hash('down') then
		self.input.y = -1
	elseif action_id == hash('left') then
		self.input.x = -1
	elseif action_id == hash('right') then
		self.input.x = 1
	end

	if action_id == hash('shoot') or action_id == hash('touch') then
		if action.pressed then
			shoot(self)
		end
	end
end