components {
  id: "move_platform_script"
  component: "/game/entities/platforms/move_platform.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"move_platform\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlas_textures_tilesource/tile_2.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 1.5\n"
  "restitution: 0.5\n"
  "group: \"move_platform\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 8.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 94.52381\n"
  "  data: 21.481781\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
