components {
  id: "block_script"
  component: "/game/entities/block_script.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"block_blue\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 5.0\n"
  "  y: 5.0\n"
  "  z: 5.0\n"
  "  w: 5.0\n"
  "}\n"
  "size {\n"
  "  x: 64.0\n"
  "  y: 64.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/textures/block.atlas\"\n"
  "}\n"
  ""
}
