local match3 = require('scenes.shared.match3')
local input = require('core.systems.input')
local game_manager = require('game.managers.game_manager')

local BOARD_URL = hash('/board')

local function init_cursor_view()
	msg.post('#sprite_cursor', 'disable')
	msg.post('#sprite_highlight', 'disable')
end

local function swap_block(self)
	
end

local function update_cursor_view(self)
	if self.selected then
		local local_pos = match3.slot_to_screen(self.selected.x, self.selected.y)
		local board_world_pos = go.get_world_position(BOARD_URL)
		local final_pos = board_world_pos + local_pos
		final_pos.z = 1
		go.set_position(final_pos)

		msg.post('#sprite_highlight', 'enable')
	end
end

local function keyboard_update_cursor(self, action_id, action)
	local x, y = self.selected.x, self.selected.y
	if self.selected.x > match3.board_width - 1 then
		self.selected.x = match3.board_width - 1
	elseif self.selected.x < 0 then
		self.selected.x = 0
	elseif self.selected.y > match3.board_height - 1 then
		self.selected.y = match3.board_height - 1
	elseif self.selected.y < 0 then
		self.selected.y = 0
	end

	if action_id == input.UP and action.pressed then
		self.selected = { x = x, y = y + 1 }
	elseif action_id == input.DOWN and action.pressed then
		self.selected = { x = x, y = y - 1 }
	elseif action_id == input.LEFT and action.pressed then
		self.selected = { x = x - 1, y = y }
	elseif action_id == input.RIGHT and action.pressed then
		self.selected = { x = x + 1, y = y }
	end
	update_cursor_view(self)
end

local function mouse_update_cursor(self, action_id, action)
	local board_world_pos = go.get_world_position(BOARD_URL)
	local click_slot_x, click_slot_y = match3.screen_to_slot(board_world_pos, action.x, action.y)
	if not match3.on_board(click_slot_x, click_slot_y) then
		self.selected = nil
		update_cursor_view(self)
		return
	end

	if self.selected == nil then
		self.selected = { x = click_slot_x, y = click_slot_y }
	else
		local prey_x = self.selected.x
		local prey_y = self.selected.y
		if prey_x == click_slot_x and prey_y == click_slot_y then
			self.selected = nil
		elseif match3.is_neighbor(prey_x, prey_y, click_slot_x, click_slot_y) then
			match3.swap_block(prey_x, prey_y, click_slot_x, click_slot_y)
			self.selected = nil
		else
			self.selected = { x = click_slot_x, y = click_slot_y }
		end
		
	end
	update_cursor_view(self)
end

---@package
---@param self player_script.script
function init(self)
	msg.post('.', 'acquire_input_focus')
	msg.post(BOARD_URL, 'set_parent', { keep_world_transform = 0 })

	init_cursor_view()
	
	-- 结构 { x = #, y = # }
	self.selected = { x = 0, y = 0 }
	self.locked = false
	update_cursor_view(self)
end

local function debugger(self)
	local debug_text_show_pos = vmath.vector3(25, 710, 1)
	msg.post('@render:', 'draw_debug_text', {
		position = debug_text_show_pos,
		color = vmath.vector4(0, 1, 0, 1),
		text = string.format('slot index: (%d, %d)', self.selected.x, self.selected.y)
	})
end

---@package
---@param self player_script.script
---@param dt number
function update(self, dt)

	if game_manager.get_state() == 'remove_state' then
		msg.post('.', 'release_input_focus')
	elseif game_manager.get_state() == 'play_state' then
		msg.post('.', 'acquire_input_focus')
	end

	-- debug mode
	-- debugger(self)
end


---@package
---@param self player_script.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	
end

---@package
---@param self player_script.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
	if action_id == input.CLICK and action.pressed then
		mouse_update_cursor(self, action_id, action)
	end
	
	if action_id == input.UP or action_id == input.DOWN or 
	action_id == input.LEFT or action_id == input.RIGHT then
		keyboard_update_cursor(self, action_id, action)
	end
end