local monarch = require "monarch.monarch"
local transitions = require('monarch.transitions.gui')
local input = require('core.systems.input')

function init(self)
    msg.post(".", "acquire_input_focus")
    local transition = transitions.create(gui.get_node('root'))
        .show_in(transitions.fade_in, gui.EASING_OUTQUAD, 0.4, 0)
        .show_out(transitions.fade_out, gui.EASING_INQUAD, 0.6, 0)
    -- .back_in(transitions.fade_in, gui.EASING_OUTQUAD, 1, 0)
    -- .back_out(transitions.fade_out, gui.EASING_INQUAD, 1, 0)
    monarch.on_transition('main_menu', transition)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    monarch.on_message(message_id, message, sender)

    if message_id == hash('show_level_1') then
        monarch.show('level_1')
    end
end

function on_input(self, action_id, action)
    if action_id == input.CLICK and action.pressed then
        msg.post('#', 'show_level_1')
    end
end

function on_reload(self)
end
