local monarch = require "monarch.monarch"
local transitions = require('monarch.transitions.gui')
local Input = require('core.systems.input')

function init(self)
    msg.post(".", "acquire_input_focus")
    local transition = transitions.create(gui.get_node('root'))
        .show_in(transitions.fade_in, gui.EASING_OUTQUAD, 0.4, 0)
        .show_out(transitions.fade_out, gui.EASING_INQUAD, 0.6, 0)
        .back_in(transitions.fade_in, gui.EASING_OUTQUAD, 0.4, 0)
        .back_out(transitions.fade_out, gui.EASING_INQUAD, 0.6, 0)
    monarch.on_transition('main_menu', transition)

    -- 2. 获取节点 (建议在 init 中获取并缓存)
    local tip_node = gui.get_node('tip')

    -- 3. 启动闪烁动画 (Ping Pong 模式)
    -- 解释：从当前值(默认为1) 动画到 0，线性过度，耗时0.5秒，延迟0秒
    -- 关键点：gui.PLAYBACK_LOOP_PINGPONG 会自动让数值在 1 -> 0 -> 1 之间无限往返
    gui.animate(tip_node, 'color.w', 0, gui.EASING_LINEAR, 2, 0, nil, gui.PLAYBACK_LOOP_PINGPONG)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    monarch.on_message(message_id, message, sender)

    if message_id == hash('show_level_1') then
        monarch.show('level_1')
    end
end

function on_input(self, action_id, action)
    if action_id == Input.CLICK or action_id == Input.START then
        if action.pressed then
            msg.post('#', 'show_level_1')
        end
    end
end

function on_reload(self)
end
