local dialog_data = require 'game.contents.dialog_text'
local audio_manager = require 'main.managers.audio_manager'
local druid = require("druid.druid")

local ALL_TEXTS = dialog_data.dialog_text -- 方便访问文本数组 --
-- 定义文本数组的长度 --
local TEXT_COUNT = #ALL_TEXTS

local hide_pos = vmath.vector3(300, -550, 0)
local end_pos = vmath.vector3(300, -190, 0)


function init(self)
	msg.post('.', 'acquire_input_focus')
	-- 获取和设置对话框节点 --
	self.dialog_node = gui.get_node('dialog_box')
	gui.set_position(self.dialog_node, hide_pos)
	self.is_show = false
	
	-- 获取和设置对话框文本节点 --
	self.dialog_text_node = gui.get_node('dialog_text')

	-- 1. 初始化文本索引 --
	self.current_dialog_index = 1
	-- 2. 显示第一个文本 --
	gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])

	-- 点击gui的动画效果锁 --
	self.slots_node_is_scaled = {}

	-- 使用druid拓展：初始化创建实例 --
	self.druid = druid.new(self)

	-- 创建多个节点，用名字数组一次性声明 --
	local item_names = {
		'command_frag_1',
		'command_frag_2',
		'command_frag_3',
		'command_frag_4',
		'command_frag_5',
	}
	self.items = {}
	for i, name in ipairs(item_names) do
		local node = gui.get_node(name)
		-- 记录初始位置（作为回弹位置） --
		local start_positon = gui.get_position(node)
		self.items[i] = {
			name = name, 
			node = node,
			start_positon = start_positon,
			drag = nil,
			placed_slot = nil
		}
	end

	-- 创建每个item的drag组件（循环创建），注意闭包捕获 --
	for i, item in ipairs(self.items) do
		
		local node = item.node -- 为闭包创建本地引用 --
		local item_index = i -- 为闭包创建本地索引 --
		local start_position = item.start_position
		
		-- druid的拖拽功能 --
			-- 创建druid拖拽按钮功能 ， 第一个参数可以使节点对象或者节点id（这里我们传节点对象）--
			-- 初始化拖拽并在拖拽回调中移动拖拽节点 --
		local drag = self.druid:new_drag(node, function(_, dx, dy) 
			local px = gui.get(node, 'position.x')
			local py = gui.get(node, 'position.y')
			gui.set(node, 'position.x', px + dx)
			gui.set(node, 'position.y', py + dy)
		end)

		-- 拖拽的回调函数 --
		drag.on_drag_start:subscribe(function() 
			print('drag start!')
		end)
		drag.on_drag:subscribe(function(_, dx, dy) 
			print('dragging!')
		end)
		drag.on_drag_end:subscribe(function() 
			print('drag end!')
		end)
	end	

	-- -- 保存动画的起始位置 --
	-- local start_positon_1 = gui.get_position(self.drag_1.node)
	-- self.drag_1.on_drag_end:subscribe(function() 
	-- 	gui.animate(self.drag_1.node, 'position', start_positon_1, gui.EASING_OUTBACK, 0.2)
	-- end)

end

function next_dialog_text(self)	
	-- 检查是否还有下一个文本
	if self.current_dialog_index < TEXT_COUNT then
		-- 移动到下一个文本 --
		self.current_dialog_index = self.current_dialog_index + 1
		-- 更新文本内容 --
		gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])

		return true -- 表示还有文本（方便调试） --
	else
		-- 文本已读取完毕，执行结束逻辑 --
		print("文本已到头")
		-- 隐藏对话框并重置索引
		self.is_show = true
		self.current_dialog_index = 1
		return false -- 表示文本结束（方便调试） --
	end
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

local function dialog_show(self)
	if self.is_show then 
		gui.animate(self.dialog_node, gui.PROP_POSITION, hide_pos, gui.EASING_OUTCUBIC, 0.8)
		self.is_show = false
	else
		gui.animate(self.dialog_node, gui.PROP_POSITION, end_pos, gui.EASING_OUTCUBIC, 0.8)
		gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])
	end
end

local function click_command(self, action)
	for i = 1, 3 do
		local node_id = 'command_'..i
		local node = gui.get_node(node_id)
		if gui.pick_node(node, action.x, action.y) and action.pressed then
			gui.animate(node, gui.PROP_SCALE, vmath.vector3(0.85, 0.85, 1.0), gui.EASING_OUTBACK, 0.05, 0, function() 
				gui.animate(node, gui.PROP_SCALE, vmath.vector3(1.0, 1.0, 1.0), gui.EASING_OUTBACK, 0.2)
			end)
			audio_manager.play_sfx('click')
			self.slots_node_is_scaled[i] = true
			print('click!')
		end
	end
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
	if message_id == hash('dialog_start') then
		dialog_show(self)
	end
end

function on_input(self, action_id, action)
	if action_id == hash('touch') and action.pressed then
		-- 点击对话框 --
		if gui.pick_node(self.dialog_node, action.x, action.y) and action.pressed then
			next_dialog_text(self)
			audio_manager.play_sfx('click')
		end

		-- 点击指令系统 --
		click_command(self, action)
	end
	
	return self.druid:on_input(action_id, action)
end

function on_reload(self)
	
end
