local dialog_data = require 'game.contents.dialog_text'
local audio_manager = require 'main.managers.audio_manager'
local ALL_TEXTS = dialog_data.dialog_text -- 方便访问文本数组 --
-- 定义文本数组的长度 --
local TEXT_COUNT = #ALL_TEXTS


local hide_pos = vmath.vector3(300, -550, 0)
local end_pos = vmath.vector3(300, -190, 0)

function init(self)

	-- 获取和设置对话框节点 --
	self.dialog_node = gui.get_node('dialog_box')
	gui.set_position(self.dialog_node, hide_pos)
	self.is_show = false
	
	-- 获取和设置对话框文本节点 --
	self.dialog_text_node = gui.get_node('dialog_text')

	-- 1. 初始化文本索引 --
	self.current_dialog_index = 1
	-- 2. 显示第一个文本 --
	gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])

	self.slots_node_is_scaled = {}
	msg.post('.', 'acquire_input_focus')
end

function next_dialog_text(self)	
	-- 检查是否还有下一个文本
	if self.current_dialog_index < TEXT_COUNT then
		-- 移动到下一个文本 --
		self.current_dialog_index = self.current_dialog_index + 1
		-- 更新文本内容 --
		gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])

		return true -- 表示还有文本（方便调试） --
	else
		-- 文本已读取完毕，执行结束逻辑 --
		print("文本已到头")
		-- 隐藏对话框并重置索引
		self.is_show = true
		self.current_dialog_index = 1
		return false -- 表示文本结束（方便调试） --
	end
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)

end

function dialog_show(self)
	if self.is_show then 
		gui.animate(self.dialog_node, gui.PROP_POSITION, hide_pos, gui.EASING_OUTCUBIC, 0.8)
		self.is_show = false
	else
		gui.animate(self.dialog_node, gui.PROP_POSITION, end_pos, gui.EASING_OUTCUBIC, 0.8)
		gui.set_text(self.dialog_text_node, ALL_TEXTS[self.current_dialog_index])
	end
end

function click_command(self, action)
	for i = 1, 4 do
		local node_id = 'command_'..i
		local node = gui.get_node(node_id)
		if gui.pick_node(node, action.x, action.y) and action.pressed then
			gui.animate(node, gui.PROP_SCALE, vmath.vector3(0.85, 0.85, 1.0), gui.EASING_OUTBACK, 0.05, 0, function() 
				gui.animate(node, gui.PROP_SCALE, vmath.vector3(1.0, 1.0, 1.0), gui.EASING_OUTBACK, 0.2)
			end)
			audio_manager.play_sfx('click')
			self.slots_node_is_scaled[i] = true
			print('click!')
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash('dialog_start') then
		dialog_show(self)
	end
end

function on_input(self, action_id, action)
	if action_id == hash('touch') and action.pressed then
		-- 点击对话框 --
		if gui.pick_node(self.dialog_node, action.x, action.y) and action.pressed then
			next_dialog_text(self)
			audio_manager.play_sfx('click')
		end

		-- 点击指令系统 --
		click_command(self, action)
		
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
