local BgMovement = require('scenes.shared.BgMovement')
local game_manager = require('game.managers.game_manager')


local function player_init(self)
    local index = game_manager.selected_player or 1
    local spawn_pos = vmath.vector3(960, 68, 0)
    local factory_id = '/player_init#factory_1'
    
    if index == 2 then
        factory_id = '/player_init#factory_2'
    elseif index == 3 then
        factory_id = '/player_init#factory_3'
    end
    local player_id = factory.create(factory_id, spawn_pos)
    msg.post('/ball', 'player_id_is', { id = player_id })
end

---@package
---@param self level.script
function init(self)
    player_init(self)
end

---@package
---@param self level.script
---@param dt number
function update(self, dt)
    BgMovement.bg_rotate(go.get_id('/bg_deco'), nil, dt)
    
    if game_manager.get_state() == 'play_state' then
        if game_manager.get_brick_count() <= 0 then
            game_manager.set_state('next_level_state')
            game_manager.set_level()
            msg.post('main:/game_loader', 'goto_score_scene')
        end
    end

    print(game_manager.get_level())
    
    -- 调试模块
end

---@package
---@param self level.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('player_dead') then
        game_manager.set_state('score_state')
        msg.post('main:/game_loader', 'goto_score_scene')
    end
end

