local BgMovement = require('scenes.shared.BgMovement')
local game_state = require('scenes.shared.game_state')

local function player_init()
    local index = game_state.selected_player_index or 1
    local spawn_pos = vmath.vector3(960, 68, 0)
    print("正在加载玩家类型: " .. index)
    local factory_id = '/player_init#factory_1'
    if index == 2 then
        factory_id = '/player_init#factory_2'
    elseif index == 3 then
        factory_id = '/player_init#factory_3'
    end
    local player_id = factory.create(factory_id, spawn_pos)
end

---@package
---@param self level_1.script
function init(self)
    player_init()
end

---@package
---@param self level_1.script
---@param dt number
function update(self, dt)
    BgMovement.bg_rotate(go.get_id('/bg_deco'), nil, dt)
    -- 调试模块
end

