local game_manager = require('game.managers.game_manager')

local function bricks_maker(self)
    local component = '#level_maker'
    local spawn_center_pos = go.get_position()

    local num_rows = math.random(1, 5)
    local num_cols = math.random(6, 12)

    local total_w = num_cols * self.brick_w
    local total_h = num_rows * self.brick_h

    local start_x = spawn_center_pos.x - total_w / 2 + self.brick_w / 2
    local start_y = spawn_center_pos.y + total_h / 2 + self.brick_h / 2
    local pos = vmath.vector3(start_x, start_y, 0)

    local highest_color_type = math.min(3, self.level % 5 + 2)

    for y = 1, num_rows do
        pos.x = start_x
        
        -- 随机一种模式：默认固定、颜色交替、间隔
        local row_mode = math.random(1, 3)
        -- 颜色交替
        local color_type_1 = math.random(1, highest_color_type)
        local color_type_2 = math.random(1, highest_color_type)
        -- 间隔
        local skip_remainder = math.random(0, 1)
        
        for x = 1, num_cols do
            local current_type = color_type_1
            local should_spawn = true

            if row_mode == 1 then
                current_type = color_type_1
            elseif row_mode == 2 then
                if (x % 2 == 1) then
                    current_type = color_type_2
                else
                    current_type = color_type_1
                end
            elseif row_mode == 3 then
                current_type = color_type_1
                if (x % 2 == skip_remainder) then
                    should_spawn = not should_spawn
                end
            end

            if should_spawn then
                local properties = { type = current_type }
                local brick = factory.create(component, pos, nil, properties)
                self.total_bricks = self.total_bricks + 1
            end

            pos.x = pos.x + self.brick_w
        end

        pos.y = pos.y - self.brick_h
    end
    
    game_manager.set_brick_count(self.total_bricks)
end

---@package
---@param self level_maker_manager.script
function init(self)
    math.randomseed(os.time())
    
    self.level = game_manager.get_level()
    self.total_bricks = 0
    self.brick_w = go.get('/brick#sprite', 'size.x')
    self.brick_h = go.get('/brick#sprite', 'size.y')

    bricks_maker(self)

    -- 调试模块
end



