embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"2\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 10.0\n"
  "  y: 10.0\n"
  "  z: 10.0\n"
  "  w: 10.0\n"
  "}\n"
  "size {\n"
  "  x: 200.0\n"
  "  y: 200.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/textures/generated/my_default.tilesource\"\n"
  "}\n"
  ""
}
