local game_manager = require('game.managers.game_manager')


function init(self)
	msg.post(".", "acquire_input_focus")
	self.score = game_manager.get_score()
	self.score_node = gui.get_node('final_score')
	local text = 'Your final score: ' .. self.score
	gui.set_text(self.score_node, text)
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if action_id == hash('start') then
		game_manager.set_state('title_state')
		msg.post('main:/game_loader', 'goto_main_menu')
	end
end

function on_reload(self)
end
