local game_manager = require('game.managers.game_manager')

go.property('type', 1)
go.property('score_value', 100)

---@package
---@param self brick.script
function init(self)
	local anim_name = 'brick_00' .. self.type
	sprite.play_flipbook('#sprite', anim_name)
end

---@package
---@param self brick.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
	if message_id == hash('collision_response') and message.group == hash('ball') then
		if self.type == 1 then
			local score_to_add = self.score_value * self.type
			msg.post('/level_gui', 'add_score', { score = score_to_add })
			game_manager.brick_destoryed()
			go.delete()
		elseif self.type >= 2 then
			local score_to_add = self.score_value * self.type
			msg.post('/level_gui', 'add_score', { score = score_to_add })
			self.type = self.type - 1
			local next_anim = string.format('brick_%03d', self.type)
			sprite.play_flipbook('#sprite', next_anim)
		end
	end
end