-- 随机方向 --
-- 方向控制 --

local audio_manager = require('main.audio_manager')
go.property('speed', 400)

local function set_random_dir(self)
    local pos = go.get_position()
    pos = self.init_pos

    local direction = vmath.vector3(math.random(2) == 1 and 10 or -10, math.random(-5, 5), 0)

    if direction.x > 0 then
        self.is_p1_serve = true
        msg.post('/gui', 'p1_serve')
    else
        self.is_p2_serve = true
        msg.post('/gui', 'p2_serve')
    end
    
    self.direction = vmath.normalize(direction)
    -- self.direction = direction
    self.speed = 400
    self.paddle_bounce_dir = 1
    go.set_position(pos)
    -- 调试模块 --
end

function clear_serve(self)
    self.is_p1_serve = false
    self.is_p2_score = false
end

---@package
---@param self ball.script
function init(self)
    math.randomseed(os.time())
    
    self.speed = 400
    self.direction = vmath.vector3()
    self.init_pos = go.get_position()
    self.paddle_bounce_dir = 0
    self.is_p1_serve = false
    self.is_p2_serve = false

    set_random_dir(self)
end

---@package
---@param self ball.script
---@param dt number
function update(self, dt)
    ---- 根据游戏状态来执行对应状态下的操作 ----
    if game_state == 'start' then
        clear_serve(self)
    elseif game_state == 'serve' then

    elseif game_state == 'play' then
        -- 获取位置
        local pos = go.get_position()
        -- 计算位置更新
        pos = pos + self.direction * self.speed * dt
        go.set_position(pos)

        -- 检测上下屏幕反弹
        if pos.y > SCREEN_HEIGHT - 18 then
            audio_manager.play_sfx('wall_hit')
            self.direction.y = -self.direction.y
            msg.post('/paddle_ai', 'ball_info', { dir = self.direction, speed = self.speed })
            
        elseif pos.y < 0 + 18 then
            audio_manager.play_sfx('wall_hit')
            self.direction.y = -self.direction.y
            msg.post('/paddle_ai', 'ball_info', { dir = self.direction, speed = self.speed })
        end

        -- 检测进球得分
        if pos.x > SCREEN_WIDTH then
            audio_manager.play_sfx('score')
            msg.post('/gui#game', 'player1_score', { score = 1 })
            msg.post('/main_manager', 'change_to_serve')
            self.is_p2_serve = true
            set_random_dir(self)
        elseif pos.x < 0 then
            audio_manager.play_sfx('score')
            msg.post('/gui#game', 'player2_score', { score = 1 })
            msg.post('/main_manager', 'change_to_serve')
            self.is_p1_serve = true
            set_random_dir(self)
        end

        msg.post('/paddle_ai', 'ball_info', { dir = self.direction, speed = self.speed })
    elseif game_state == 'done' then

    end

    -- 游戏性改动：改进球的方向
    if math.abs(self.direction.x) < 0.5 then
        self.direction.x = math.random(-1, 1)
    end
    
    if self.speed > 1200 then
        self.speed = 1200
    end

    -- 调试模块 --

end

---@package
---@param self ball.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('contact_point_response') then
        if message.group == hash('paddle') then
            audio_manager.play_sfx('paddle_hit')

            local newpos = go.get_position() + message.normal * message.distance
            go.set_position(newpos)

            -- 计算反弹方向 --
            -- self.direction.x = -self.direction.x
            -- self.direction.y = math.random(-1, 1)
            local dot = vmath.dot(self.direction, message.normal)
            local direction = self.direction - 2 * dot * message.normal
            self.direction = vmath.normalize(direction)

            self.speed = self.speed * 1.2
            
            msg.post('/paddle_ai', 'ball_info', { dir = self.direction, speed = self.speed })
        end
    end
    
    if message_id == hash('paddle_bounce') then
        self.paddle_bounce_dir = message.bounce_dir
    end
end