go.property('speed', 400)



---@package
---@param self paddle.script
function init(self)
    msg.post('.', 'acquire_input_focus')

    self.height = go.get('#sprite', 'size.y') * 0.5
    self.input = vmath.vector3()
end

---@package
---@param self paddle.script
---@param dt number
function update(self, dt)
    local pos = go.get_position()
    if self.input.y == 1 then
        pos = pos + self.input * self.speed * dt
    elseif self.input.y == -1 then
        pos = pos + self.input * self.speed * dt
    end
    self.input.y = 0

    pos.y = vmath.clamp(pos.y, 0+self.height/2, SCREEN_HEIGHT-self.height/2)
    go.set_position(pos)
end

---@package
---@param self paddle.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == hash('up') then
        self.input.y = 1
    elseif action_id == hash('down') then
        self.input.y = -1
    end
end