go.property('speed', 400)



---@package
---@param self paddle.script
function init(self)
    msg.post('.', 'acquire_input_focus')

    self.height = go.get('#sprite', 'size.y') * 0.5
    self.direction = vmath.vector3()

    -- 初始反弹量 反弹系数 中心偏移量
    self.bounce_power = 1
    self.bounce_multi = 1.5
    self.is_moving_up = false
    self.is_moving_down = false
end

---@package
---@param self paddle.script
---@param dt number
function update(self, dt)
    local pos = go.get_position()
    if self.direction.y == 1 then
        pos = pos + self.direction * self.speed * dt
    elseif self.direction.y == -1 then
        pos = pos + self.direction * self.speed * dt
    end
    self.direction.y = 0

    pos.y = vmath.clamp(pos.y, 0 + self.height / 2, SCREEN_HEIGHT - self.height / 2)
    go.set_position(pos)
    
    -- 球拍与球的反弹手感更新 --
    -- local ball_pos = go.get_position('/ball')
    -- local paddle_center = go.get_position().y
    -- local ball_offset = ball_pos.y - paddle_center
    
    -- if ball_pos.y > pos.y and self.is_moving_up then
    --     local bounce_m = 1 * self.bounce_power + self.bounce_multi * ball_offset
    --     msg.post('/ball', 'paddle_bounce', { bounce_m = bounce_m })
    -- elseif ball_pos.y < pos.y and self.is_moving_down then
    --     local bounce_m = -1 * self.bounce_power - self.bounce_multi * ball_offset
    --     msg.post('/ball', 'paddle_bounce', { bounce_m = bounce_m })
    -- end

    -- 调试模块 --
end

---@package
---@param self paddle.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == hash('up') then
        self.direction.y = 1
        self.is_moving_up = true
    elseif action_id == hash('down') then
        self.direction.y = -1
        self.is_moving_down = true
    end
end
