go.property('speed', 400)


---- 实现敌方球拍AI ----
---- 步骤1：当球过屏幕中线时开始实时获取球的位置 ----
---- 步骤2：将球的


---@package
---@param self paddle.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    
    self.height = go.get('#sprite', 'size.y') * 0.5
    self.direction = vmath.vector3()
    self.move = 0
end

---@package
---@param self paddle.script
---@param dt number
function update(self, dt)
    local pos = go.get_position()
    local ball_pos = go.get_position('/ball')
    
    

    -- -- 第一种AI：硬追踪，追踪位置，高难度 ----
    -- if game_state == 'play' then
    --     -- 死区防抖动 --
    --     local move_zone = 10
    --     -- 这个是核心 --
    --     local dy = ball_pos.y - pos.y

    --     if math.abs(dy) < move_zone then
    --         self.direction.y = 0
    --     elseif dy > 0 and ball_pos.x > SCREEN_WIDTH / 2 then
    --         self.direction.y = 1
    --     elseif dy < 0 and ball_pos.x > SCREEN_WIDTH / 2 then
    --         self.direction.y = -1
    --     end
    -- end

    pos.y = pos.y + self.direction.y * self.speed * dt

    pos.y = vmath.clamp(pos.y, 0 + self.height / 2, SCREEN_HEIGHT - self.height / 2)
    go.set_position(pos)

    -- 调试模块 --
end

---@package
---@param self paddle_ai.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    -- 第二种AI：软追踪，追踪方向，中等难度
    -- 之前缺少对齐逻辑（需要追踪球与球拍的位置变化量），即dy变量
    -- 计算步骤
    -- 1.判断球是否飞向AI，以及什么时候AI会做出判断
    -- 2.计算球到达paddle需要的时间
        -- 距离 = 球拍x坐标 - 球x坐标
        -- 时间 = 距离 / 球坐标
    -- 3.预测球的y坐标
        -- 球的y坐标 = 球的y坐标 + 球的速度 * 时间
    -- 4.处理墙壁反弹
    -- 5.移动到预测位置

    if message_id == hash('ball_info') then
        local paddle_pos = go.get_position()
        local ball_pos = go.get_position('/ball')
        local ball_dir = message.dir
        local ball_speed = message.speed
        local dead_zone = 10
        
        if ball_dir.x < 0 then
            self.direction.y = 0
            return
        end

        local distance = paddle_pos.x - ball_pos.x
        local time_to_reach = distance / ball_pos.x
        local predicted_y = ball_pos.y + ball_speed * time_to_reach

        -- predicted_y = calculate_bounce(predicted_y)

        local dy = predicted_y - paddle_pos.y
        if math.abs(dy) < dead_zone then
            self.direction.y = 0
        elseif dy > 0 and ball_pos.x > SCREEN_WIDTH / 2 then
            self.direction.y = 1
        elseif dy < 0 and ball_pos.x > SCREEN_WIDTH / 2 then
            self.direction.y = -1
        end

        -- 调试模块 --
    end
end