local audio_manager = require 'main.managers.audio_manager'

function init(self)
	self.scaled = false

	msg.post('.', 'acquire_input_focus')
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
	if action_id == hash('touch') and action.pressed then
		msg.post('view#game', 'dialog_start')
		audio_manager.play_sfx('click')
		
		if not self.scaled then
			go.animate('.', 'scale', go.PLAYBACK_ONCE_FORWARD, vmath.vector3(0.3, 0.3, 0), go.EASING_OUTBACK, 0.5)
			self.scaled = true
		else
			go.animate('.', 'scale', go.PLAYBACK_ONCE_FORWARD, vmath.vector3(0.2, 0.2, 0), go.EASING_OUTBACK, 0.5)
			self.scaled = false
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
