function init(self)
	msg.post(".", "acquire_input_focus")

	self.move_speed = 0.1
	self.position = go.get_position()
	self.target_pos = self.position
end

function update(self, dt)
	local distance = self.target_pos - self.position
	self.position = self.position + distance * self.move_speed * dt
	if vmath.length(distance) < 1 then
		self.position = self.target_pos
	end
	go.set_position(self.position)
end

function on_input(self, action_id, action)
	if action.pressed then
		self.target_pos = vmath.vector3(action.x, action.y, 0)
		print('target_pos:', self.target_pos)
		print('ship_pos:', self.position)
	end
end