local monarch = require "monarch.monarch"
local event = require('event.event')

function init(self)
    msg.post(".", "acquire_input_focus")
    print('new!')
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash('encounter_started') then
        monarch.show('level_3')
    end
end

function on_input(self, action_id, action)
    if action_id == hash('menu') then
        monarch.show('wild_menu', nil, {
            options_text = {'bag', 'atlas', 'exit'},
            on_select = event.create(function (index)
                if index == 3 then monarch.back() end
            end)
        })
    end

    if action_id == hash('back') and action.pressed then
        monarch.back()
    end
end

function on_reload(self)
end
