local monarch = require "monarch.monarch"
local event = require('event.event')
local Input = require('core.systems.input')
local SoundController =require('core.components.sound_controller')


function init(self)
    msg.post(".", "acquire_input_focus")
    monarch.show('level_2_dialogue')
end

function final(self)

end

function update(self, dt)
    
end

function on_message(self, message_id, message, sender)
    
    if message_id == hash('encounter_started') then
        monarch.show('level_3')
    end
end

function on_input(self, action_id, action)
    if action_id == Input.MENU then
        monarch.show('wild_menu')
        SoundController.play('Thip', SoundController.GROUP_SFX)
    end
end

function on_reload(self)
end