local monarch = require "monarch.monarch"

function init(self)
    msg.post(".", "acquire_input_focus")
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash('encounter_started') then
        monarch.show('level_3')
    end
end

function on_input(self, action_id, action)
    if action_id == hash('menu') then
        monarch.show('wild_menu')
    end
end

function on_reload(self)
end
