local GameData = require('data.game_data')
local Input = require('core.systems.input')
local utils = require('core.utils.utils')
local PokemonData = require('data.pokemon_data')
local PokemonEngine = require('game.entities.pokemon.pokemon_engine')
local Flow = require('core.systems.flow')

local spawn_player_pokemon
local spawn_opponent_pokemon
local spawn_factory
local battle_opening
local battle_flow
local set_init_data
local debugger

local player_pokemon_start_pos = vmath.vector3(-300, 456, 1)
local opponent_pokemon_start_pos = vmath.vector3(2200, 861, 1)


---@package
---@param self battle_controller.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    set_init_data(self)

    spawn_player_pokemon(self)
    spawn_opponent_pokemon(self)

    battle_opening(self)

    battle_flow(self)

    debugger(self)
end

set_init_data = function (self)
    self.is_loop = true
end

---@package
---@param self battle_controller.script
---@param dt number
function update(self, dt)
    Flow.update(dt)
end

---@package
---@param self battle_controller.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    if action_id == Input.BACK and action.pressed then
        Flow.stop()
        self.is_loop = false
        print("收到停止指令！")
    end
end

spawn_player_pokemon = function (self)
    self.player_pokemon_pos = go.get_position('/player_pokemon_pos')
    print(self.player_pokemon_pos)


    local id = GameData.player_first_pokemon.id
    self.player_pokemon_id = spawn_factory(self, id, player_pokemon_start_pos)
    local sprite_front_url = msg.url(nil, self.player_pokemon_id, 'sprite_front')
    local sprite_back_url = msg.url(nil, self.player_pokemon_id, 'sprite_back')
    msg.post(sprite_front_url, 'disable')
    msg.post(sprite_back_url, 'enable')
    print('spawn player pokemon')
end

spawn_opponent_pokemon = function (self)
    self.opponent_pokemon_pos = go.get_position('/opponent_pokemon_pos')
    print(self.opponent_pokemon_pos)
    local random_pokemon = PokemonEngine.get_random_pokemon(PokemonData)
    self.opponent_pokemon = PokemonEngine(random_pokemon, math.random(2, 6))

    self.opponent_pokemon_id = spawn_factory(self, self.opponent_pokemon.id, opponent_pokemon_start_pos)
    print('spawn opponent pokemon')
end

spawn_factory = function (self, id, pos)
    local url = '/pokemon_factory/factory_pokemon#factory_' .. id
    local position = pos
    local properties = { pokemon_id = id }
    local scale = 5.0

    local id = factory.create(url, position, nil, properties, scale)
    return id
end

battle_opening = function (self)
    -- shadow
    local player_shadow_target_pos = go.get_position('/shadow_1')
    go.set_position(vmath.vector3(-430, 273, 0), '/shadow_1')
    go.animate('/shadow_1', 'position', go.PLAYBACK_ONCE_FORWARD, player_shadow_target_pos, go.EASING_LINEAR, 1, 0, function ()
            --pokemon
            go.set_position(vmath.vector3(-300, 456, 1), self.player_pokemon_id)
            go.animate(self.player_pokemon_id, 'position', go.PLAYBACK_ONCE_FORWARD, self.player_pokemon_pos,
            go.EASING_LINEAR, 1)
    end)

    -- shadow
    local opponent_shadow_target_pos = go.get_position('/shadow_2')
    go.set_position(vmath.vector3(2300, 744, 0), '/shadow_2')
    go.animate('/shadow_2', 'position', go.PLAYBACK_ONCE_FORWARD, opponent_shadow_target_pos, go.EASING_LINEAR, 1, 0, function ()
            --pokemon
            go.set_position(vmath.vector3(2000, 861, 1), self.opponent_pokemon_id)
            go.animate(self.opponent_pokemon_id, 'position', go.PLAYBACK_ONCE_FORWARD, self.opponent_pokemon_pos,
            go.EASING_LINEAR, 1)
    end)
end

debugger = function (self)
    pprint(GameData.player_first_pokemon.id)
    pprint(self.opponent_pokemon.id)
end

battle_flow = function (self)
    Flow.start(function ()
        print('战斗开始！')
        -- while self.is_loop do
        --     Flow.wait(1)
        --     print('玩家攻击！')

        --     if not self.is_loop then break end

        --     Flow.wait(1)
        --     print('敌人攻击')
        -- end
        Flow.wait(4)
        print('敌人攻击！')
        print('开始扣血')
        msg.post('/monarch#level_3', 'animate_hp')
        Flow.wait_for_signal('hp_anim_finshed')
        print('血条动画播放完毕，继续后续逻辑')
    end)
end