local GameData = require('data.game_data')
local Input = require('core.systems.input')
local utils = require('core.utils.utils')
local PokemonData = require('data.pokemon_data')
local PokemonEngine = require('game.entities.pokemon.pokemon_engine')
local Flow = require('core.systems.flow')
local StateStack = require('core.systems.state_stack')
local States = require('core.systems.battle_states.battle_states')
local BattleMechanics = require('core.systems.battle_mechanics')

local spawn_player_pokemon
local spawn_opponent_pokemon
local spawn_factory
local battle_opening
local execute_battle_flow
local set_init_data
local show_message
local get_battle_data

local debugger

local player_pokemon_start_pos = vmath.vector3(-300, 456, 1)
local opponent_pokemon_start_pos = vmath.vector3(2200, 861, 1)

set_init_data = function (self)
    self.execute_battle_flow = execute_battle_flow
    self.show_message = show_message
end

---@package
---@param self battle_controller.script
function init(self)
    msg.post('.', 'acquire_input_focus')

    set_init_data(self)

    spawn_player_pokemon(self)
    spawn_opponent_pokemon(self)

    get_battle_data(self)

    battle_opening(self)

    debugger(self)
    
    -- 创建状态栈，并将 self 作为 owner 传入
    self.stack = StateStack.create(self)

    -- 初始状态：主菜单
    self.stack.push(States.ActionMenu)
end

---@package
---@param self battle_controller.script
---@param dt number
function update(self, dt)
    self.stack.update(dt)
    Flow.update(dt)
end

---@package
---@param self battle_controller.script
---@param message_id hash
---@param message table
---@param sender url
function on_message(self, message_id, message, sender)
    if message_id == hash('command_fight') then
        -- 1. 记录玩家的指令数据
        print("攻击！")
        self.current_turn_data = {
            player_action = "Tackle",  -- 撞击
            enemy_action = "Tail Whip" -- 摇尾巴
        }

        -- 2. 切换到结算状态
        -- 一旦 push，控制权就到了 ResolutionState 手里，玩家点不了菜单了
        self.stack.push(States.Resolution)

    elseif message_id == hash('command_ability') then
        -- 处理能力逻辑...
        print("能力！")
    end
end

---@package
---@param self battle_controller.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    -- 1. 先把输入喂给状态栈
    local handled = self.stack.on_input(action_id, action)

    -- 2. 如果状态栈（比如 Resolution）返回了 true，
    --    那么这个输入就被“吞”掉了，不会传给 GUI
    if handled then
        return true
    end

    -- 3. 如果状态栈返回 false（比如 ActionMenu），
    --    Defold 会自动把输入继续传给 GUI 脚本。
    return false
end


get_battle_data = function (self)
    self.player_data = GameData.player_first_pokemon
    self.opponent_data = self.opponent_pokemon
end


spawn_player_pokemon = function (self)
    self.player_pokemon_pos = go.get_position('/player_pokemon_pos')

    local id = GameData.player_first_pokemon.id
    self.player_pokemon_id = spawn_factory(self, id, player_pokemon_start_pos)
    local sprite_front_url = msg.url(nil, self.player_pokemon_id, 'sprite_front')
    local sprite_back_url = msg.url(nil, self.player_pokemon_id, 'sprite_back')
    msg.post(sprite_front_url, 'disable')
    msg.post(sprite_back_url, 'enable')
    print('spawn player pokemon')
end

spawn_opponent_pokemon = function (self)
    self.opponent_pokemon_pos = go.get_position('/opponent_pokemon_pos')
    local random_pokemon = PokemonEngine.get_random_pokemon(PokemonData)
    self.opponent_pokemon = PokemonEngine(random_pokemon, math.random(2, 6))

    self.opponent_pokemon_id = spawn_factory(self, self.opponent_pokemon.id, opponent_pokemon_start_pos)
    print('spawn opponent pokemon')
end

spawn_factory = function (self, id, pos)
    local url = '/pokemon_factory/factory_pokemon#factory_' .. id
    local position = pos
    local properties = { pokemon_id = id }
    local scale = 5.0

    local id = factory.create(url, position, nil, properties, scale)
    return id
end

battle_opening = function (self)
    -- shadow
    local player_shadow_target_pos = go.get_position('/shadow_1')
    go.set_position(vmath.vector3(-430, 273, 0), '/shadow_1')
    go.animate('/shadow_1', 'position', go.PLAYBACK_ONCE_FORWARD, player_shadow_target_pos, go.EASING_LINEAR, 1, 0, function ()
            --pokemon
            go.set_position(vmath.vector3(-300, 456, 1), self.player_pokemon_id)
            go.animate(self.player_pokemon_id, 'position', go.PLAYBACK_ONCE_FORWARD, self.player_pokemon_pos,
            go.EASING_LINEAR, 1)
    end)

    -- shadow
    local opponent_shadow_target_pos = go.get_position('/shadow_2')
    go.set_position(vmath.vector3(2300, 744, 0), '/shadow_2')
    go.animate('/shadow_2', 'position', go.PLAYBACK_ONCE_FORWARD, opponent_shadow_target_pos, go.EASING_LINEAR, 1, 0, function ()
            --pokemon
            go.set_position(vmath.vector3(2000, 861, 1), self.opponent_pokemon_id)
            go.animate(self.opponent_pokemon_id, 'position', go.PLAYBACK_ONCE_FORWARD, self.opponent_pokemon_pos,
            go.EASING_LINEAR, 1)
    end)
end

-- 修改：执行具体的回合剧本
execute_battle_flow = function (self)
    print("【剧本开始，数据驱动】")

    -- 1.定义攻防双方
    local attacker = self.player_data -- 暂定玩家永远先手（以后再加速度判断）
    local defender = self.opponent_data

    -- A.玩家回合
    local move_name = '撞击'
    -- 显示消息
    self:show_message(attacker.name .. '使用了' .. move_name)
    -- 播放攻击动画
    msg.post(self.player_pokemon_id, 'play_attack_anim', { id = 'attack'})
    Flow.wait(1.0) -- 模拟动画时间
    -- 核心：计算伤害
    local damage = BattleMechanics.calculate_damege(attacker, defender, 40)
    print('计算伤害：' .. damage)
    -- 核心：更新数据模型
    defender:take_damage(damage)
    -- 核心；通知UI进行更新（传入百分比）
    local target_percent = defender:get_hp_percent()
    print('目标剩余血量百分比；' .. target_percent)
    local message = { target = 'enemy' , to_percent = target_percent }
    msg.post('/monarch#level_3', 'animate_hp', message)
    -- 等待UI动画完成
    Flow.wait_for_signal('animate_hp_done')
    --  显示伤害评价
    self:show_message('造成了' .. damage .. '点伤害')
    -- 检查是否战斗结束
    if defender:is_fainted() then
        self:show_message(defender.name .. '倒下了！')
        -- 胜利逻辑
        msg.post('/monarch#level_3', 'won')
        return
    end

    -- B.敌人回合
    attacker, defender = defender, attacker
    local move_name = '撞击'
    -- 显示消息
    self:show_message(attacker.name .. '使用了' .. move_name)
    -- 播放攻击动画
    msg.post(self.player_pokemon_id, 'play_attack_anim', { id = 'attack'})
    Flow.wait(1.0) -- 模拟动画时间
    -- 核心：计算伤害
    local damage = BattleMechanics.calculate_damege(attacker, defender, 40)
    print('计算伤害：' .. damage)
    -- 核心：更新数据模型
    defender:take_damage(damage)
    -- 核心；通知UI进行更新（传入百分比）
    local target_percent = defender:get_hp_percent()
    print('目标剩余血量百分比；' .. target_percent)
    local message = { target = 'player' , to_percent = target_percent }
    msg.post('/monarch#level_3', 'animate_hp', message)
    -- 等待UI动画完成
    Flow.wait_for_signal('animate_hp_done')
    --  显示伤害评价
    self:show_message('造成了' .. damage .. '点伤害')
    -- 检查是否战斗结束
    if defender:is_fainted() then
        self:show_message(defender.name .. '倒下了！')
        -- 胜利逻辑
        msg.post('/monarch#level_3', 'won')
        return
    end

    print("【回合结束】")
    self.stack.pop()

    -- -- 1. 玩家攻击表现
    -- local text = self.player_data.name .. '发动了攻击！'
    -- self:show_message(text)
    -- Flow.wait(1.0)
    -- -- 2. 假设这里有一个 GO 的攻击动画
    -- -- go.animate(self.player_pokemon_id, ...)
    -- -- 如果有回调，就用 Flow.wait_for_signal，这里我们先用等待模拟
    -- Flow.wait(0.5)
    -- -- 3. 敌人受击表现与扣血
    -- print("敌人掉血...")
    -- -- 通知 GUI 播血条动画
    -- msg.post("/monarch#level_3", "animate_hp", { target = "enemy", amount = -20 })
    -- -- 【关键】等待 GUI 传回信号
    -- Flow.wait_for_signal("hp_anim_finished")
    -- Flow.wait(1.0)
    -- -- 计算伤害后显示第二条信息
    -- local text = '这非常有效！'
    -- self:show_message(text)
    -- -- 4. 检查是否结束
    -- if self.enemy_data.hp <= 0 then
    --     -- 胜负逻辑...
    -- end
    -- -- 5. 【极其重要】剧本演完了，告诉状态栈：我们可以回菜单了
    -- print("【剧本结束】")
    -- self.stack.pop() -- 弹出 Resolution 状态，回到 MoveMenu 或 ActionMenu
    -- -- -- 6.对战胜利
    -- -- msg.post('/monarch#level_3', 'won')
end

show_message = function (self, text)
    -- 1. 压入消息状态
    self.stack.push(States.Message, text)
    -- 2. 利用Flow系统，阻塞，直到收到信号
    Flow.wait_for_signal('message_closed')
end


debugger = function(self)
    pprint(GameData.player_first_pokemon.id)
    pprint(self.opponent_pokemon.id)

    -- 调试：看看引用的到底是个什么东西
    print("--- 调试 StateStack 模块 ---")
    pprint(StateStack)
end
