components {
  id: "player"
  component: "/game/entities/player/player.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"paddle\"\n"
  "mask: \"ball\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -157.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 157.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 4\n"
  "    count: 1\n"
  "  }\n"
  "  data: 146.49663\n"
  "  data: 37.654118\n"
  "  data: 10.0\n"
  "  data: 37.66799\n"
  "  data: 37.66799\n"
  "}\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Rectangle 21\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 65.0\n"
  "  y: 30.0\n"
  "  z: 65.0\n"
  "  w: 30.0\n"
  "}\n"
  "size {\n"
  "  x: 384.0\n"
  "  y: 70.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/textures/arts.atlas\"\n"
  "}\n"
  ""
}
