local lume = require('lib.thirdparty.lume')

go.property('current_move_dir', 0)
go.property('speed', 700)


---@package
---@param self player.script
function init(self)
    msg.post('.', 'acquire_input_focus')
    self.speed = self.speed
    self.direction = vmath.vector3()
    self.width = go.get('#sprite', 'size.x')
    self.moving_left = false
    self.moving_right = false
end

---@package
---@param self player.script
---@param dt number
function update(self, dt)
    local pos = go.get_position()
    pos.x = pos.x + self.current_move_dir * self.speed * dt
    pos.x = lume.clamp(pos.x, 0 + self.width / 2, SCREEN_WIDTH - self.width / 2)
    go.set_position(pos)
    
    -- 调试模块
end

---@package
---@param self player.script
---@param action_id hash
---@param action on_input.action
---@return boolean|nil
function on_input(self, action_id, action)
    -- 1. 独立更新每个按键的状态
    if action_id == hash('left') then
        if action.pressed then
            self.moving_left = true
        elseif action.released then
            self.moving_left = false
        end
    elseif action_id == hash('right') then
        if action.pressed then
            self.moving_right = true
        elseif action.released then
            self.moving_right = false
        end
    end

    -- 2. 综合计算方向 (核心逻辑) Lua 中布尔值不能直接相减，转换一下
    local val_right = self.moving_right and 1 or 0
    local val_left = self.moving_left and 1 or 0
    self.current_move_dir = val_right - val_left

    -- 公式：方向 = 右输入 - 左输入
    -- 右按左不按: 1 - 0 = 1 (向右)
    -- 左按右不按: 0 - 1 = -1 (向左)
    -- 都按: 1 - 1 = 0 (不动)
    -- 都不按: 0 - 0 = 0 (不动)
end