embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"gameframe\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 20.0\n"
  "  y: 20.0\n"
  "  z: 20.0\n"
  "  w: 20.0\n"
  "}\n"
  "size {\n"
  "  x: 1920.0\n"
  "  y: 1080.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "offset: 0.3\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/textures/arts.atlas\"\n"
  "}\n"
  ""
}
