

local function bricks_maker(self)
    local component = '#level_maker'
    local spawn_center_pos = go.get_position()
    local total_w = self.num_cols * self.brick_w
    local total_h = self.num_rows * self.brick_h
    local start_x = spawn_center_pos.x - total_w / 2 + self.brick_w / 2
    local start_y = spawn_center_pos.y + total_h / 2 + self.brick_h / 2
    local pos = vmath.vector3(start_x, start_y, 0)

    for r = 1, self.num_rows do
        pos.x = start_x
        for c = 1, self.num_cols do
            factory.create(component, pos)
            pos.x = pos.x + self.brick_w
            
        end
        pos.y = pos.y - self.brick_h
    end

end

---@package
---@param self level_maker_manager.script
function init(self)
    math.randomseed(os.time())
    self.brick_w = go.get('/brick#sprite', 'size.x')
    self.brick_h = go.get('/brick#sprite', 'size.y')
    self.num_rows = math.random(1, 5)
    self.num_cols = math.random(7, 13)
    bricks_maker(self)
    -- 调试模块
    print(self.num_cols)
    print(self.num_rows)
end

